### Class Activity:

In [1]:
import pandas as pd
import numpy as np

##### Series:

In [2]:
#series is a labelled 1D array --> with indexing
s= pd.Series([10, 20, 30], name= 'amount', index= ['S1', 'S2', 'S3'])
print(s)

S1    10
S2    20
S3    30
Name: amount, dtype: int64

In [3]:
s[-1:]

S3    30
Name: amount, dtype: int64

##### Dataframe:

In [4]:
# Dataframe is a 2D tabular data with rows and columns:
df = pd.DataFrame({'amount':[10, 20, 30]})
print(df)

   amount
0      10
1      20
2      30

In [11]:
# Creating dataframe from a dictionary:
data = {
    "id": [1,2,3,4],
    "name": ["Alex", "Maria", "John", "Sara"],
    "age": [21, 19, 22, 20],
    "score": [85.0, 78, 90, 88]
}
df = pd.DataFrame(data)
print(df)

   id   name  age  score
0   1   Alex   21   85.0
1   2  Maria   19   78.0
2   3   John   22   90.0
3   4   Sara   20   88.0

In [12]:
# reading file from CSV:
student_df= pd.read_csv("students.csv")
print(student_df)

   id   name  age  score
0   1   Alex   21     85
1   2  Maria   19     78
2   3   John   22     90
3   4   Sara   20     88
4   5  David   18     72

In [13]:
student_df.head(2)

   id   name  age  score
0   1   Alex   21     85
1   2  Maria   19     78

##### Appending a dataframe:

In [14]:

# 1. append data
student_df= pd.concat([student_df, df], ignore_index= True)
student_df

   id   name  age  score
0   1   Alex   21   85.0
1   2  Maria   19   78.0
2   3   John   22   90.0
3   4   Sara   20   88.0
4   5  David   18   72.0
5   1   Alex   21   85.0
6   2  Maria   19   78.0
7   3   John   22   90.0
8   4   Sara   20   88.0

##### Drop duplicates:

In [15]:
# drop duplicates from the dataframe [Alex, Maria]:
student_df.drop_duplicates(inplace= True)

In [16]:
student_df

   id   name  age  score
0   1   Alex   21   85.0
1   2  Maria   19   78.0
2   3   John   22   90.0
3   4   Sara   20   88.0
4   5  David   18   72.0

### Filtering:

In [17]:
student_df[student_df['age'] > 20][['name', 'age']]

   name  age
0  Alex   21
2  John   22

In [18]:
student_df.loc[student_df['age'] > 20, ['name', 'age']]

   name  age
0  Alex   21
2  John   22

In [19]:
student_df.iloc[2:, 1:3]

    name  age
2   John   22
3   Sara   20
4  David   18

##### Groupby

In [20]:
data = {
    "Name": ["Alex", "Riya", "John", "Tony", "Sam"],
    "Department": ["HR", "IT", "IT", "HR", "IT"],
    "Salary": [30000, 50000, 45000, 32000, 52000]
}
df = pd.DataFrame(data)
print(df)

   Name Department  Salary
0  Alex         HR   30000
1  Riya         IT   50000
2  John         IT   45000
3  Tony         HR   32000
4   Sam         IT   52000

In [21]:
df.groupby("Department")['Salary'].mean()

Department
HR    31000.0
IT    49000.0
Name: Salary, dtype: float64

##### Sort values

In [22]:
df.sort_values("Salary", ascending= False)

   Name Department  Salary
4   Sam         IT   52000
1  Riya         IT   50000
2  John         IT   45000
3  Tony         HR   32000
0  Alex         HR   30000

In [23]:
#Which department pays more?
df.groupby("Department")['Salary'].mean().sort_values(ascending= False)

Department
IT    49000.0
HR    31000.0
Name: Salary, dtype: float64

In [24]:
# Total salary in each department:
df.groupby("Department")['Salary'].sum()

Department
HR     62000
IT    147000
Name: Salary, dtype: int64

In [25]:
df.groupby(["Department", "Name"])['Salary'].sum()

Department  Name
HR          Alex    30000
            Tony    32000
IT          John    45000
            Riya    50000
            Sam     52000
Name: Salary, dtype: int64

__________________

### Lab Assignments:

##### Q. 1 — Create a DataFrame

In [26]:
data= [{'order_id': 101, 'city': 'London', 'amount': 45.50, 'status': 'complete'},
       {'order_id': 102, 'city': 'Manchester', 'amount': 18.80, 'status': 'cancelled'},
       {'order_id': 103, 'city': 'London', 'amount': 62.25, 'status': 'complete'},
       {'order_id': 104, 'city': 'Leeds', 'amount': 30.00, 'status': 'complete'}]
                    
order_df= pd.DataFrame(data)
order_df

   order_id        city  amount     status
0       101      London   45.50   complete
1       102  Manchester   18.80  cancelled
2       103      London   62.25   complete
3       104       Leeds   30.00   complete

In [27]:
order_df.columns

Index(['order_id', 'city', 'amount', 'status'], dtype='object')

In [28]:
order_df.shape

(4, 4)

##### Q.2 — Create and Read Three CSV Batches

In [29]:
batch_1=pd.read_csv('case1.csv', sep= ';')
batch_2=pd.read_csv('case2.csv', sep= ';')
batch_3=pd.read_csv('case3.csv', sep= ';')

 
print("Batch 1 rows:", len(batch_1))
print("Batch 2 rows:", len(batch_2))
print("Batch 3 rows:", len(batch_3))

Batch 1 rows: 2
Batch 2 rows: 2
Batch 3 rows: 2

##### Q.3 — Combine the CSV Batches

In [32]:
all_order_df= pd.concat([batch_1, batch_2, batch_3], ignore_index= True)
all_order_df

   order_id        city  amount     status
0       201      London   45.50   complete
1       202  Manchester   18.00  cancelled
2       203     Bristol   62.25   complete
3       204      London   27.40   complete
4       205       Leeds   34.80   complete
5       206  Manchester   51.10   complete

In [33]:
all_order_df.shape

(6, 4)

##### Q. 4 — MCQ: DataFrame

Which description best matches a Pandas DataFrame?

Answer: A. A two-dimensional labelled table with rows and columns.

#### Q. 5 — Write and Read an Excel File

In [34]:
# creating a dataframe:
products = pd.DataFrame({
    "product_id": [1, 2, 3],
    "product_name": ["Desk Lamp", "Office Chair", "Notebook Set"],
    "price_gbp": [24.99, 89.50, 8.75],
})

products

   product_id  product_name  price_gbp
0           1     Desk Lamp      24.99
1           2  Office Chair      89.50
2           3  Notebook Set       8.75

In [45]:
# write it to .xlsx file
products.to_excel('products.xlsx',sheet_name="products", index= False)

# To resolve the error: ModuleNotFoundError: No module named 'openpyxl'
#!pip install openpyxl

In [46]:
# Verify if the dataframe is exported to the excel file:
print(pd.read_excel("products.xlsx"))

   product_id  product_name  price_gbp
0           1     Desk Lamp      24.99
1           2  Office Chair      89.50
2           3  Notebook Set       8.75

#### Q. 6 — Read a JSON File

writing the data to json and reading as a dataframe :

In [49]:
cust_data= [
  {"customer_id": 1, "name": "Amelia Clarke", "city": "London"},
  {"customer_id": 2, "name": "Oliver Bennett", "city": "Manchester"},
  {"customer_id": 3, "name": "Aisha Khan", "city": "Leeds"}
]

cust_df= pd.DataFrame(cust_data)
cust_df.to_json("customers.json")

In [50]:
customers= pd.read_json("customers.json")
customers.head()

   customer_id            name        city
0            1   Amelia Clarke      London
1            2  Oliver Bennett  Manchester
2            3      Aisha Khan       Leeds

In [52]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  3 non-null      int64
 1   name         3 non-null      object
 2   city         3 non-null      object
dtypes: int64(1), object(2)
memory usage: 96.0+ bytes

#### Q. 7 — Select Only Required Columns

Using the combined orders DataFrame from Part 1, create a new DataFrame containing only:

- order_id

- city

- amount_gbp

Then select only the amount_gbp column and check its Python object type.

In [53]:
all_order_df

   order_id        city  amount     status
0       201      London   45.50   complete
1       202  Manchester   18.00  cancelled
2       203     Bristol   62.25   complete
3       204      London   27.40   complete
4       205       Leeds   34.80   complete
5       206  Manchester   51.10   complete

In [55]:
orders= all_order_df[['order_id', 'city', 'amount']]
orders

   order_id        city  amount
0       201      London   45.50
1       202  Manchester   18.00
2       203     Bristol   62.25
3       204      London   27.40
4       205       Leeds   34.80
5       206  Manchester   51.10

In [57]:
orders['amount'].dtype

dtype('float64')

#### Q. 8 — MCQ: Inspecting Data

Which command gives the number of rows and columns as a tuple?

Answer: C. df.shape

#### Q. 9 — Filter Completed Orders


Using all_orders, keep only rows where: status == complete

In [60]:
all_order_df[all_order_df['status'] == 'complete']

   order_id        city  amount    status
0       201      London   45.50  complete
2       203     Bristol   62.25  complete
3       204      London   27.40  complete
4       205       Leeds   34.80  complete
5       206  Manchester   51.10  complete

In [135]:
all_order_df[(all_order_df['amount'] > 30) & (all_order_df['status'] == 'complete')][['order_id', 'city']]

   order_id        city
0       201      London
2       203     Bristol
4       205       Leeds
5       206  Manchester

#### Q. 10 — Clean Missing Values

Perform these tasks:

- count nulls in each column;
- replace missing city with "Unknown";
- remove rows where amount_gbp is missing.

In [64]:
# 1. create a dataframe:

df = pd.DataFrame({
    "order_id": [301, 302, 303, 304],
    "city": ["London", None, "Leeds", "Bristol"],
    "amount_gbp": [45.50, 20.00, None, 30.00],
})

df

   order_id     city  amount_gbp
0       301   London        45.5
1       302     None        20.0
2       303    Leeds         NaN
3       304  Bristol        30.0

In [65]:
df.isnull().sum()

order_id      0
city          1
amount_gbp    1
dtype: int64

`city` has 1 null value in total and similarly `amount_gbp` has 1 null value.

In [67]:
# Replace missing value in `city` with `Unknown`
df['city']= df['city'].fillna('Unknown')
df

   order_id     city  amount_gbp
0       301   London        45.5
1       302  Unknown        20.0
2       303    Leeds         NaN
3       304  Bristol        30.0

In [70]:
# Drop rows if amount is missing:
df.dropna(subset=['amount_gbp'], inplace= True)
df

   order_id     city  amount_gbp
0       301   London        45.5
1       302  Unknown        20.0
3       304  Bristol        30.0

#### Q. 11 — Rename and Create New Columns

- id -> order_id
- price -> unit_price_gbp
- qty -> quantity

In [73]:
df = pd.DataFrame({
    "id": [401, 402, 403],
    "price": [20.00, 50.00, 12.50],
    "qty": [2, 1, 4],
})

print("Before rename:")
print(df)

Before rename:
    id  price  qty
0  401   20.0    2
1  402   50.0    1
2  403   12.5    4

In [72]:
df_renamed= df.rename(columns={'id': 'order_id', 'price': 'unit_price_gbp', 'qty': ' quantity'})
print("After rename:")
print(df_renamed)

After rename:
   order_id  unit_price_gbp   quantity
0       401            20.0          2
1       402            50.0          1
2       403            12.5          4

#### Q. 12 — MCQ: Missing Values

You want to keep the row but replace a missing city with "Unknown". Which method is the best fit?

Answer:  B. fillna()

#### Q. 13 — Sort Sales from Highest to Lowest

Using all_orders, sort by amount_gbp from highest to lowest.

In [77]:
orders.sort_values('amount', ascending= False)

   order_id        city  amount
2       203     Bristol   62.25
5       206  Manchester   51.10
0       201      London   45.50
4       205       Leeds   34.80
3       204      London   27.40
1       202  Manchester   18.00

#### Q. 14 — Revenue by City

Using only completed orders, calculate:

- total revenue by city;
- order count by city.
- Sort the result by revenue from highest to lowest.

In [87]:
all_order_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  6 non-null      int64
 1   city      6 non-null      object
 2   amount    6 non-null      float64
 3   status    6 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 324.0+ bytes

In [83]:
# total revenue by city: Series

all_order_df[all_order_df['status'] == 'complete'].groupby('city')['amount'].sum().reset_index(name= 'total_revenue')

         city  total_revenue
0     Bristol          62.25
1       Leeds          34.80
2      London          72.90
3  Manchester          51.10

In [90]:
# total revenue by city: Dataframe

all_order_df[all_order_df['status'] == 'complete'].groupby('city')[['amount']].agg(total_revenue=('amount', 'sum')).reset_index()

         city  total_revenue
0     Bristol          62.25
1       Leeds          34.80
2      London          72.90
3  Manchester          51.10

Both produces same results, but the first returns a Series and the second returns a Dataframe. reset_index() works differently for both.

In [84]:
#order count by city
all_order_df[all_order_df['status'] == 'complete'].groupby('city')['order_id'].count().reset_index(name= 'order_count')

         city  order_count
0     Bristol            1
1       Leeds            1
2      London            2
3  Manchester            1

In [85]:
# Sort the result by revenue from highest to lowest.
all_order_df[all_order_df['status'] == 'complete'].groupby('city')['amount'].sum().reset_index(name= 'total_revenue').sort_values('total_revenue', ascending= False)

         city  total_revenue
2      London          72.90
0     Bristol          62.25
3  Manchester          51.10
1       Leeds          34.80

#### Q. 15 — Merge Orders with Store Details


Merge them on store_id.

In [92]:
orders = pd.DataFrame({
    "order_id": [501, 502, 503, 504],
    "store_id": ["LDN-01", "MAN-02", "LDN-01", "LDS-04"],
    "amount_gbp": [45.50, 30.00, 62.25, 20.00],
})

stores = pd.DataFrame({
    "store_id": ["LDN-01", "MAN-02", "LDS-04"],
    "city": ["London", "Manchester", "Leeds"],
    "region": ["South", "North", "North"],
})

print("Orders Dataframe:")
print(orders)
print("\nStores Dataframe: ")
print(stores)

Orders Dataframe:
   order_id store_id  amount_gbp
0       501   LDN-01       45.50
1       502   MAN-02       30.00
2       503   LDN-01       62.25
3       504   LDS-04       20.00

Stores Dataframe:
  store_id        city region
0   LDN-01      London  South
1   MAN-02  Manchester  North
2   LDS-04       Leeds  North

In [94]:
merged_df= pd.merge(orders, stores, how= 'left', on='store_id')
merged_df

   order_id store_id  amount_gbp        city region
0       501   LDN-01       45.50      London  South
1       502   MAN-02       30.00  Manchester  North
2       503   LDN-01       62.25      London  South
3       504   LDS-04       20.00       Leeds  North

#### Q. 16 — MCQ: Merge

Why is a left merge useful when orders is the left DataFrame?


D. It keeps every order and adds matching store details when available.

#### Q. 17 — Build a Three-Batch Cleaning Flow

In [95]:
#Create three CSV batches
df1= pd.read_csv('batch_1.csv')
df2= pd.read_csv('batch_2.csv')
df3= pd.read_csv('batch_3.csv')

print("Three CSV batch files saved as a dataframe: \n")
print(df1)
print(df2)
print(df3)

Three CSV batch files saved as a dataframe:

   order_id        city  amount_gbp    status
0       601      London        45.5  complete
1       602  Manchester        -5.0  complete
   order_id     city  amount_gbp     status
0       603      NaN        30.0   complete
1       604  Bristol        20.0  cancelled
   order_id    city  amount_gbp    status
0       601  London        45.5  complete
1       605   Leeds        50.0  complete

Faced issue initially while concatenating:

**TypeError: cannot concatenate object of type '<class 'str'>'; only Series and DataFrame objs are valid**

Because I have used quotation marks for the dataframe ['df1', 'df2', 'df3'].

In [106]:
# Combine the batches
combined_orders= pd.concat([df1, df2, df3], ignore_index= True)
combined_orders

   order_id        city  amount_gbp     status
0       601      London        45.5   complete
1       602  Manchester        -5.0   complete
2       603         NaN        30.0   complete
3       604     Bristol        20.0  cancelled
4       601      London        45.5   complete
5       605       Leeds        50.0   complete

Create:
- valid_orders;
- rejected_orders.
  
Reject:

- non-positive amount;
- missing city;
- duplicate order_id

In [132]:
invalid_mask = ((combined_orders['city'].isna())|
    (combined_orders['amount_gbp'] < 0)|
    (combined_orders.duplicated(subset= 'order_id', keep= 'first'))
               )

rejected_orders= combined_orders.loc[invalid_mask].copy()

valid_orders= combined_orders.loc[~invalid_mask].copy()

print("Subset of rejected orders: ")
print(rejected_orders)
print("\nSubset of accepted orders:")
print(valid_orders)

Subset of rejected orders:
   order_id        city  amount_gbp    status
1       602  Manchester        -5.0  complete
2       603         NaN        30.0  complete
4       601      London        45.5  complete

Subset of accepted orders:
   order_id     city  amount_gbp     status
0       601   London        45.5   complete
3       604  Bristol        20.0  cancelled
5       605    Leeds        50.0   complete

In [133]:
import numpy as np

duplicated_mask= combined_orders.duplicated(subset= 'order_id', keep= 'first')
conditions= [rejected_orders['city'].isna(),
            rejected_orders['amount_gbp'] < 0,
            duplicated_mask.loc[rejected_orders.index]
            ]

reasons= ['missing_city', 'non-positive amount', 'duplicate order_id']

rejected_orders['rejection_reason']= np.select(conditions, reasons, default= 'Unknown')

rejected_orders

   order_id        city  amount_gbp    status     rejection_reason
1       602  Manchester        -5.0  complete  non-positive amount
2       603         NaN        30.0  complete         missing_city
4       601      London        45.5  complete   duplicate order_id

In [134]:
source_count= len(combined_orders)
valid_rows= len(valid_orders)
rejected_rows= len(rejected_orders)

print(f"Source Rows: {source_count}")
print(f"\nValid Rows: {valid_rows}")
print(f"\nInavlid Rows: {rejected_rows}")

Source Rows: 6

Valid Rows: 3

Inavlid Rows: 3

#### Q. 20 — Create a Business Summary


Using the valid orders from Q. 17:

keep only completed orders;

calculate total revenue by city;

calculate order count by city;

sort highest revenue first.

In [141]:
valid_orders[valid_orders['status'] == 'complete'].groupby('city')['amount_gbp'].sum().reset_index(name='total_revenue').sort_values('total_revenue', ascending= False)

     city  total_revenue
0   Leeds           50.0
1  London           45.5

_____________________________________________________________________

In [ ]:
from numpy.random import randn

In [ ]:
np.random.seed(101)

In [ ]:
df= pd.DataFrame(randn(5,4), ['A', 'B', 'C', 'D', 'E'], ['W', 'X', 'Y', 'Z'])
df

#### To select a row from dataframe:

In [ ]:
df.loc['E']

In [ ]:
df.iloc[4] #index based

#### selecting subset from a dataframe:

In [ ]:
df.loc['B', 'Y']

In [ ]:
df.loc[['A', 'C'], ['Y', 'Z']]  #subset in dataframe

#### Conditional Selection:

In [ ]:
df[df > 0]

In [ ]:
df[df['Z'] < 0]

In [ ]:
df[df['W'] > 0]['X']

#### multiple conditional statements

In [ ]:
df[(df['W'] > 0) & (df ['Y'] < 0)]

_____________________________________