## Part 1 — ETL and ELT

#### Q. 1 — Perform a Small ETL Flow

A supplier sends this data:

import pandas as pd
 
source = pd.DataFrame({
    "product_id": [101, 102, 103, 104],
    "price_gbp": ["25.50", "invalid", "12.00", "40.00"],
})

In [1]:
import pandas as pd
import numpy as np

In [2]:
source = pd.DataFrame({
    "product_id": [101, 102, 103, 104],
    "price_gbp": ["25.50", "invalid", "12.00", "40.00"],
})

In [3]:
source

   product_id price_gbp
0         101     25.50
1         102   invalid
2         103     12.00
3         104     40.00

Create a clean DataFrame where:

- price_gbp is numeric;
- invalid prices are rejected;
- only valid rows are loaded into clean_products

In [4]:
df= source.copy()

In [5]:
df.loc[df['price_gbp'] == 'invalid', 'price_gbp'] = 0

In [6]:
df

   product_id price_gbp
0         101     25.50
1         102         0
2         103     12.00
3         104     40.00

In [7]:
df.dtypes

product_id     int64
price_gbp     object
dtype: object

In [8]:
df.astype({'price_gbp':'float'}).dtypes

product_id      int64
price_gbp     float64
dtype: object

In [9]:
df

   product_id price_gbp
0         101     25.50
1         102         0
2         103     12.00
3         104     40.00

In [10]:
clean_df= source.copy()

In [11]:
clean_df

   product_id price_gbp
0         101     25.50
1         102   invalid
2         103     12.00
3         104     40.00

#### Q. 2 — Simulate a Small ELT Flow

In [12]:
# Fetching the source
 
source = pd.DataFrame({
    "order_id": [201, 202, 203],
    "amount_gbp": ["45.50", "30.00", "bad"],
})

In [13]:
# Ingest raw orders:

In [14]:
raw_orders= source.copy()
raw_orders

   order_id amount_gbp
0       201      45.50
1       202      30.00
2       203        bad

In [15]:
# removing invalid values
clean_orders= raw_orders.copy()
clean_orders.drop(clean_orders[clean_orders['amount_gbp']=='bad'].index, inplace= True)
clean_orders

   order_id amount_gbp
0       201      45.50
1       202      30.00

In [16]:
# Convert the data type to float:
clean_orders.astype({'amount_gbp':'float'}).dtypes

order_id        int64
amount_gbp    float64
dtype: object

#### Q. 3 — Choose ETL or ELT

Choose the better starting pattern.



| Requirement                                                      | ETL or ELT?               | Reason                                   |
| ---------------------------------------------------------------- | --------------------------| ---------------------------------------- |
| Invalid data must be removed before it reaches the target        | ETL                       | Data must be transformed                 |
| Raw source data should be kept first for later reprocessing      | ELT                       | Data is first Extracted and Loaded       |
| Target system has strong SQL transformation capability           | ELT                       | Data is transformed at the target system |
| Sensitive fields must be removed before loading                  | ETL                       | Data is transformed before loading       |

#### Q. 4 — MCQ: ETL

Which sequence represents ETL?

Solution:  C. Extract → Transform → Load

_____________________________________________________________

## Part 2 — Batch, Streaming, and Raw Data

#### Q. 5 — Process Three Independent Batches

In [17]:
batches = {
    "batch_1": [10, 20, 30],
    "batch_2": [40, 50],
    "batch_3": [60, 70, 80],
}

For each batch, print:
- batch name
- row count
- batch total

In [18]:
batch_count= 0
for key, value in batches.items():
    batch_count+= 1
    print(f'batch name: {key}')
    print(f"row count: {len(value)}")
print(f"batch total: {batch_count} ")

batch name: batch_1
row count: 3
batch name: batch_2
row count: 2
batch name: batch_3
row count: 3
batch total: 3

## Q. 6 — Batch or Streaming?

Choose the better processing style.

| Source                                                                   | Type           |
|------------------------------------------------------------------------- |--------------- |
|1. Supplier sends one file every night.                                   | Batch          |
|2. Payment events arrive continuously and need a result within seconds.   | Streaming      |  
|3. Finance produces one monthly report.                                   | Batch          |
|4. Website click events arrive throughout the day.                        | Streaming      |

## Q. 7 — Preserve Raw Input Before Cleaning

In [19]:
source = pd.DataFrame({
    "order_id": [301, 302, 303],
    "city": [" London ", None, "Leeds"],
    "amount_gbp": [45.50, 20.00, -5.00],
})

Create:

- raw_orders
- clean_orders

Rules for clean_orders:

- city must not be missing;
- amount must be positive;
- trim spaces from city.

Confirm that raw_orders still has all original rows.

In [20]:
source.shape

(3, 3)

In [21]:
raw_orders= source.copy()
raw_orders.shape

(3, 3)

In [22]:
clean_orders= raw_orders.copy()
# Replacing null in city for Unknown:
clean_orders.loc[clean_orders['city'].isnull()== True, 'city']= 'Unknown'

In [23]:
clean_orders

   order_id      city  amount_gbp
0       301   London         45.5
1       302   Unknown        20.0
2       303     Leeds        -5.0

In [24]:
# Amount must be positive:
clean_orders.drop(clean_orders[clean_orders['amount_gbp']<0].index, inplace= True)
clean_orders

   order_id      city  amount_gbp
0       301   London         45.5
1       302   Unknown        20.0

In [31]:
clean_orders['city']=clean_orders['city'].str.strip()
clean_orders

   order_id     city  amount_gbp
0       301   London        45.5
1       302  Unknown        20.0

In [32]:
print(f"Raw orders had {raw_orders.shape[0]} rows")
print(f"Clean orders had {clean_orders.shape[0]} rows")

Raw orders had 3 rows
Clean orders had 2 rows

## Part 3 — Staging, Transformation, and Analytics Layers

#### Q. 9 — Place Work in the Correct Layer

Classify each activity as mainly staging , transformation , or analytics .

A. Rename source columns to standard names. -> staging

B. Join orders to customers. -> transformation

C. Calculate daily revenue by city. -> analytics

D. Convert an amount column from text to numeric. -> staging

E. Create a report-ready monthly sales table. -> analytics

#### Q. 10 — Build a Staging Output

In [35]:

source = pd.DataFrame({
    "OrderID": [401, 402, 403],
    "CustomerID": [1, 2, 1],
    "Amount": ["45.50", "30.00", "20.00"],
})

source

   OrderID  CustomerID Amount
0      401           1  45.50
1      402           2  30.00
2      403           1  20.00

Create a staging DataFrame with:

- order_id
- customer_id
- amount_gbp

Convert amount_gbp to numeric.

In [36]:
staging_df= source.copy()
staging_df

   OrderID  CustomerID Amount
0      401           1  45.50
1      402           2  30.00
2      403           1  20.00

In [39]:
staging_df['Amount']= pd.to_numeric(staging_df['Amount'])
staging_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderID     3 non-null      int64
 1   CustomerID  3 non-null      int64
 2   Amount      3 non-null      float64
dtypes: float64(1), int64(2)
memory usage: 204.0 bytes

#### Q. 11 — Build an Analytics Output

Use this complete dataset:

In [40]:
orders = pd.DataFrame({
    "order_id": [501, 502, 503, 504],
    "city": ["London", "Leeds", "London", "Manchester"],
    "amount_gbp": [45.50, 30.00, 62.25, 50.00],
    "status": ["complete", "complete", "complete", "cancelled"],
})

orders

   order_id        city  amount_gbp     status
0       501      London       45.50   complete
1       502       Leeds       30.00   complete
2       503      London       62.25   complete
3       504  Manchester       50.00  cancelled

Create a report containing:

- city
- completed_revenue_gbp

In [47]:
orders.loc[orders['status'] == 'complete'].groupby('city')['amount_gbp'].sum().reset_index(name= 'completed_revenue_gbp')

     city  completed_revenue_gbp
0   Leeds                  30.00
1  London                 107.75

#### Q. 12 — MCQ: Staging

Which task is most suitable for a staging layer?

Solution:  D. Rename and standardize source columns before deeper transformation.

### Part 4 — Dependencies, Retries, and Backfills

#### Q. 13 — Put the Jobs in Order


BritMart has these jobs:
- load_source
- clean_orders
- build_daily_sales
- publish_report

Write the dependency chain.

load_source -> clean orders -> build_daily_sales -> publish report

#### Q. 14 — Retry or Fix First?

Choose whether an automatic retry is useful.


- Temporary network timeout: Try again might be network or server issue, reloading the page might help
- Python syntax error: Not helpful until the code is fixed	
- Database unavailable for 30 seconds: Try aghain to verify if the database is running
- Required column removed from source file: Not helpful, need to reload it again

## Q. 15 — Plan a Backfill

The daily pipeline did not run on:
- 2026-08-05
- 2026-08-06
- 2026-08-07

Create a backfill plan.

Include:

- processing order
- duplicate check
- validation after each date

Solution:


- Confirm the source data exists for the given dates.
- Check whether any partial output already exists.
- Process 2026-08-05.
- Validate counts and totals.
- Process 2026-08-06.
- Validate counts and totals.
- Process 2026-08-07.
- Validate counts and totals.
- Confirm that rerunning a date will not duplicate data.

#### Q. 16 — MCQ: Dependency

Why is a dependency needed between clean_orders and build_daily_sales?


Solution: B. To ensure the sales summary waits for clean data.

______________________________