### Data Understanding

In [1]:
import numpy as np
import pandas as pd

pd.set_option('display.max_rows', 500)

##### Load the dataset into a DataFrame called df.

In [2]:
data= pd.read_csv('nba.csv')
data

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
15,Bojan Bogdanovic,Brooklyn Nets,44.0,SG,27.0,6-8,216.0,NaN,3425510.0
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0,Oklahoma State,845059.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
20,Sergey Karasev,Brooklyn Nets,10.0,SG,22.0,6-7,208.0,NaN,1599840.0
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215.0
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0,Miami (FL),1500000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,6-10,237.0,Kansas,981348.0
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,6-10,248.0,Georgetown,947276.0
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0,Texas A&M,947276.0
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955.0
30,Arron Afflalo,New York Knicks,4.0,SG,30.0,6-5,210.0,UCLA,8000000.0
31,Lou Amundson,New York Knicks,17.0,PF,33.0,6-9,220.0,UNLV,1635476.0
32,Thanasis Antetokounmpo,New York Knicks,43.0,SF,23.0,6-7,205.0,NaN,30888.0
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000.0
34,Jose Calderon,New York Knicks,3.0,PG,34.0,6-3,200.0,NaN,7402812.0
35,Cleanthony Early,New York Knicks,11.0,SF,25.0,6-8,210.0,Wichita State,845059.0
36,Langston Galloway,New York Knicks,2.0,SG,24.0,6-2,200.0,Saint Joseph's,845059.0
37,Jerian Grant,New York Knicks,13.0,PG,23.0,6-4,195.0,Notre Dame,1572360.0
38,Robin Lopez,New York Knicks,8.0,C,28.0,7-0,255.0,Stanford,12650000.0
39,Kyle O'Quinn,New York Knicks,9.0,PF,26.0,6-10,250.0,Norfolk State,3750000.0
40,Kristaps Porzingis,New York Knicks,6.0,PF,20.0,7-3,240.0,NaN,4131720.0
41,Kevin Seraphin,New York Knicks,1.0,C,26.0,6-10,278.0,NaN,2814000.0
42,Lance Thomas,New York Knicks,42.0,SF,28.0,6-8,235.0,Duke,1636842.0
43,Sasha Vujacic,New York Knicks,18.0,SG,32.0,6-7,195.0,NaN,947276.0
44,Derrick Williams,New York Knicks,23.0,PF,25.0,6-8,240.0,Arizona,4000000.0
45,Tony Wroten,New York Knicks,5.0,SG,23.0,6-6,205.0,Washington,167406.0
46,Elton Brand,Philadelphia 76ers,42.0,PF,37.0,6-9,254.0,Duke,NaN
47,Isaiah Canaan,Philadelphia 76ers,0.0,PG,25.0,6-0,201.0,Murray State,947276.0
48,Robert Covington,Philadelphia 76ers,33.0,SF,25.0,6-9,215.0,Tennessee State,1000000.0
49,Joel Embiid,Philadelphia 76ers,21.0,C,22.0,7-0,250.0,Kansas,4626960.0
50,Jerami Grant,Philadelphia 76ers,39.0,SF,22.0,6-8,210.0,Syracuse,845059.0
51,Richaun Holmes,Philadelphia 76ers,22.0,PF,22.0,6-10,245.0,Bowling Green,1074169.0
52,Carl Landry,Philadelphia 76ers,7.0,PF,32.0,6-9,248.0,Purdue,6500000.0
53,Kendall Marshall,Philadelphia 76ers,5.0,PG,24.0,6-4,200.0,North Carolina,2144772.0
54,T.J. McConnell,Philadelphia 76ers,12.0,PG,24.0,6-2,200.0,Arizona,525093.0
55,Nerlens Noel,Philadelphia 76ers,4.0,PF,22.0,6-11,228.0,Kentucky,3457800.0
56,Jahlil Okafor,Philadelphia 76ers,8.0,C,20.0,6-11,275.0,Duke,4582680.0
57,Ish Smith,Philadelphia 76ers,1.0,PG,27.0,6-0,175.0,Wake Forest,947276.0
58,Nik Stauskas,Philadelphia 76ers,11.0,SG,22.0,6-6,205.0,Michigan,2869440.0
59,Hollis Thompson,Philadelphia 76ers,31.0,SG,25.0,6-8,206.0,Georgetown,947276.0
60,Christian Wood,Philadelphia 76ers,35.0,PF,20.0,6-11,220.0,UNLV,525093.0
61,Bismack Biyombo,Toronto Raptors,8.0,C,23.0,6-9,245.0,NaN,2814000.0
62,Bruno Caboclo,Toronto Raptors,20.0,SF,20.0,6-9,205.0,NaN,1524000.0
63,DeMarre Carroll,Toronto Raptors,5.0,SF,29.0,6-8,212.0,Missouri,13600000.0
64,DeMar DeRozan,Toronto Raptors,10.0,SG,26.0,6-7,220.0,USC,10050000.0
65,James Johnson,Toronto Raptors,3.0,PF,29.0,6-9,250.0,Wake Forest,2500000.0
66,Cory Joseph,Toronto Raptors,6.0,PG,24.0,6-3,190.0,Texas,7000000.0
67,Kyle Lowry,Toronto Raptors,7.0,PG,30.0,6-0,205.0,Villanova,12000000.0
68,Lucas Nogueira,Toronto Raptors,92.0,C,23.0,7-0,220.0,NaN,1842000.0
69,Patrick Patterson,Toronto Raptors,54.0,PF,27.0,6-9,235.0,Kentucky,6268675.0
70,Norman Powell,Toronto Raptors,24.0,SG,23.0,6-4,215.0,UCLA,650000.0
71,Terrence Ross,Toronto Raptors,31.0,SF,25.0,6-7,195.0,Washington,3553917.0
72,Luis Scola,Toronto Raptors,4.0,PF,36.0,6-9,240.0,NaN,2900000.0
73,Jason Thompson,Toronto Raptors,1.0,PF,29.0,6-11,250.0,Rider,245177.0
74,Jonas Valanciunas,Toronto Raptors,17.0,C,24.0,7-0,255.0,NaN,4660482.0
75,Delon Wright,Toronto Raptors,55.0,PG,24.0,6-5,190.0,Utah,1509360.0
76,Leandro Barbosa,Golden State Warriors,19.0,SG,33.0,6-3,194.0,NaN,2500000.0
77,Harrison Barnes,Golden State Warriors,40.0,SF,24.0,6-8,225.0,North Carolina,3873398.0
78,Andrew Bogut,Golden State Warriors,12.0,C,31.0,7-0,260.0,Utah,13800000.0
79,Ian Clark,Golden State Warriors,21.0,SG,25.0,6-3,175.0,Belmont,947276.0
80,Stephen Curry,Golden State Warriors,30.0,PG,28.0,6-3,190.0,Davidson,11370786.0
81,Festus Ezeli,Golden State Warriors,31.0,C,26.0,6-11,265.0,Vanderbilt,2008748.0
82,Draymond Green,Golden State Warriors,23.0,PF,26.0,6-7,230.0,Michigan State,14260870.0
83,Andre Iguodala,Golden State Warriors,9.0,SF,32.0,6-6,215.0,Arizona,11710456.0
84,Shaun Livingston,Golden State Warriors,34.0,PG,30.0,6-7,192.0,NaN,5543725.0
85,Kevon Looney,Golden State Warriors,36.0,SF,20.0,6-9,220.0,UCLA,1131960.0
86,James Michael McAdoo,Golden State Warriors,20.0,SF,23.0,6-9,240.0,North Carolina,845059.0
87,Brandon Rush,Golden State Warriors,4.0,SF,30.0,6-6,220.0,Kansas,1270964.0
88,Marreese Speights,Golden State Warriors,5.0,C,28.0,6-10,255.0,Florida,3815000.0
89,Klay Thompson,Golden State Warriors,11.0,SG,26.0,6-7,215.0,Washington State,15501000.0
90,Anderson Varejao,Golden State Warriors,18.0,PF,33.0,6-11,273.0,NaN,289755.0
91,Cole Aldrich,Los Angeles Clippers,45.0,C,27.0,6-11,250.0,Kansas,1100602.0
92,Jeff Ayres,Los Angeles Clippers,19.0,PF,29.0,6-9,250.0,Arizona State,111444.0
93,Jamal Crawford,Los Angeles Clippers,11.0,SG,36.0,6-5,195.0,Michigan,5675000.0
94,Branden Dawson,Los Angeles Clippers,22.0,SF,23.0,6-6,225.0,Michigan State,525093.0
95,Jeff Green,Los Angeles Clippers,8.0,SF,29.0,6-9,235.0,Georgetown,9650000.0
96,Blake Griffin,Los Angeles Clippers,32.0,PF,27.0,6-10,251.0,Oklahoma,18907726.0
97,Wesley Johnson,Los Angeles Clippers,33.0,SF,28.0,6-7,215.0,Syracuse,1100602.0
98,DeAndre Jordan,Los Angeles Clippers,6.0,C,27.0,6-11,265.0,Texas A&M,19689000.0
99,Luc Richard Mbah a Moute,Los Angeles Clippers,12.0,PF,29.0,6-8,230.0,UCLA,947276.0
100,Chris Paul,Los Angeles Clippers,3.0,PG,31.0,6-0,175.0,Wake Forest,21468695.0
101,Paul Pierce,Los Angeles Clippers,34.0,SF,38.0,6-7,235.0,Kansas,3376000.0
102,Pablo Prigioni,Los Angeles Clippers,9.0,PG,39.0,6-3,185.0,NaN,947726.0
103,JJ Redick,Los Angeles Clippers,4.0,SG,31.0,6-4,190.0,Duke,7085000.0
104,Austin Rivers,Los Angeles Clippers,25.0,PG,23.0,6-4,200.0,Duke,3110796.0
105,C.J. Wilcox,Los Angeles Clippers,30.0,SG,25.0,6-5,195.0,Washington,1159680.0
106,Brandon Bass,Los Angeles Lakers,2.0,PF,31.0,6-8,250.0,LSU,3000000.0
107,Tarik Black,Los Angeles Lakers,28.0,C,24.0,6-9,250.0,Kansas,845059.0
108,Anthony Brown,Los Angeles Lakers,3.0,SF,23.0,6-7,210.0,Stanford,700000.0
109,Kobe Bryant,Los Angeles Lakers,24.0,SF,37.0,6-6,212.0,NaN,25000000.0
110,Jordan Clarkson,Los Angeles Lakers,6.0,PG,24.0,6-5,194.0,Missouri,845059.0
111,Roy Hibbert,Los Angeles Lakers,17.0,C,29.0,7-2,270.0,Georgetown,15592217.0
112,Marcelo Huertas,Los Angeles Lakers,9.0,PG,33.0,6-3,200.0,NaN,525093.0
113,Ryan Kelly,Los Angeles Lakers,4.0,PF,25.0,6-11,230.0,Duke,1724250.0
114,Larry Nance Jr.,Los Angeles Lakers,7.0,PF,23.0,6-9,230.0,Wyoming,1155600.0
115,Julius Randle,Los Angeles Lakers,30.0,PF,21.0,6-9,250.0,Kentucky,3132240.0
116,D'Angelo Russell,Los Angeles Lakers,1.0,PG,20.0,6-5,195.0,Ohio State,5103120.0
117,Robert Sacre,Los Angeles Lakers,50.0,C,27.0,7-0,270.0,Gonzaga,981348.0
118,Louis Williams,Los Angeles Lakers,23.0,SG,29.0,6-1,175.0,NaN,7000000.0
119,Metta World Peace,Los Angeles Lakers,37.0,SF,36.0,6-7,260.0,St. John's,947276.0
120,Nick Young,Los Angeles Lakers,0.0,SF,31.0,6-7,210.0,USC,5219169.0
121,Eric Bledsoe,Phoenix Suns,2.0,PG,26.0,6-1,190.0,Kentucky,13500000.0
122,Devin Booker,Phoenix Suns,1.0,SG,19.0,6-6,206.0,Kentucky,2127840.0
123,Chase Budinger,Phoenix Suns,10.0,SF,28.0,6-7,209.0,Arizona,206192.0
124,Tyson Chandler,Phoenix Suns,4.0,C,33.0,7-1,240.0,NaN,13000000.0
125,Archie Goodwin,Phoenix Suns,20.0,SG,21.0,6-5,200.0,Kentucky,1160160.0
126,John Jenkins,Phoenix Suns,23.0,SG,25.0,6-4,215.0,Vanderbilt,981348.0
127,Brandon Knight,Phoenix Suns,3.0,PG,24.0,6-3,189.0,Kentucky,13500000.0
128,Alex Len,Phoenix Suns,21.0,C,22.0,7-1,260.0,Maryland,3807120.0
129,Jon Leuer,Phoenix Suns,30.0,PF,27.0,6-10,228.0,Wisconsin,1035000.0
130,Phil Pressey,Phoenix Suns,25.0,PG,25.0,5-11,175.0,Missouri,55722.0
131,Ronnie Price,Phoenix Suns,14.0,PG,32.0,6-2,190.0,Utah Valley,947276.0
132,Mirza Teletovic,Phoenix Suns,35.0,PF,30.0,6-9,242.0,NaN,5500000.0
133,P.J. Tucker,Phoenix Suns,17.0,SF,31.0,6-6,245.0,Texas,5500000.0
134,T.J. Warren,Phoenix Suns,12.0,SF,22.0,6-8,230.0,North Carolina State,2041080.0
135,Alan Williams,Phoenix Suns,15.0,C,23.0,6-8,260.0,UC Santa Barbara,83397.0
136,Quincy Acy,Sacramento Kings,13.0,SF,25.0,6-7,240.0,Baylor,981348.0
137,James Anderson,Sacramento Kings,5.0,SG,27.0,6-6,213.0,Oklahoma State,1015421.0
138,Marco Belinelli,Sacramento Kings,3.0,SG,30.0,6-5,210.0,NaN,6060606.0
139,Caron Butler,Sacramento Kings,31.0,SF,36.0,6-7,228.0,Connecticut,1449187.0
140,Omri Casspi,Sacramento Kings,18.0,SF,27.0,6-9,225.0,NaN,2836186.0
141,Willie Cauley-Stein,Sacramento Kings,0.0,C,22.0,7-0,240.0,Kentucky,3398280.0
142,Darren Collison,Sacramento Kings,7.0,PG,28.0,6-0,175.0,UCLA,5013559.0
143,DeMarcus Cousins,Sacramento Kings,15.0,C,25.0,6-11,270.0,Kentucky,15851950.0
144,Seth Curry,Sacramento Kings,30.0,SG,25.0,6-2,185.0,Duke,947276.0
145,Duje Dukan,Sacramento Kings,26.0,PF,24.0,6-9,220.0,Wisconsin,525093.0
146,Rudy Gay,Sacramento Kings,8.0,SF,29.0,6-8,230.0,Connecticut,12403101.0
147,Kosta Koufos,Sacramento Kings,41.0,C,27.0,7-0,265.0,Ohio State,7700000.0
148,Ben McLemore,Sacramento Kings,23.0,SG,23.0,6-5,195.0,Kansas,3156600.0
149,Eric Moreland,Sacramento Kings,25.0,PF,24.0,6-10,238.0,Oregon State,845059.0
150,Rajon Rondo,Sacramento Kings,9.0,PG,30.0,6-1,186.0,Kentucky,9500000.0
151,Cameron Bairstow,Chicago Bulls,41.0,PF,25.0,6-9,250.0,New Mexico,845059.0
152,Aaron Brooks,Chicago Bulls,0.0,PG,31.0,6-0,161.0,Oregon,2250000.0
153,Jimmy Butler,Chicago Bulls,21.0,SG,26.0,6-7,220.0,Marquette,16407500.0
154,Mike Dunleavy,Chicago Bulls,34.0,SG,35.0,6-9,230.0,Duke,4500000.0
155,Cristiano Felicio,Chicago Bulls,6.0,PF,23.0,6-10,275.0,NaN,525093.0
156,Pau Gasol,Chicago Bulls,16.0,C,35.0,7-0,250.0,NaN,7448760.0
157,Taj Gibson,Chicago Bulls,22.0,PF,30.0,6-9,225.0,USC,8500000.0
158,Justin Holiday,Chicago Bulls,7.0,SG,27.0,6-6,185.0,Washington,947276.0
159,Doug McDermott,Chicago Bulls,3.0,SF,24.0,6-8,225.0,Creighton,2380440.0
160,Nikola Mirotic,Chicago Bulls,44.0,PF,25.0,6-10,220.0,NaN,5543725.0
161,E'Twaun Moore,Chicago Bulls,55.0,SG,27.0,6-4,191.0,Purdue,1015421.0
162,Joakim Noah,Chicago Bulls,13.0,C,31.0,6-11,232.0,Florida,13400000.0
163,Bobby Portis,Chicago Bulls,5.0,PF,21.0,6-11,230.0,Arkansas,1391160.0
164,Derrick Rose,Chicago Bulls,1.0,PG,27.0,6-3,190.0,Memphis,20093064.0
165,Tony Snell,Chicago Bulls,20.0,SF,24.0,6-7,200.0,New Mexico,1535880.0
166,Matthew Dellavedova,Cleveland Cavaliers,8.0,PG,25.0,6-4,198.0,Saint Mary's,1147276.0
167,Channing Frye,Cleveland Cavaliers,9.0,PF,33.0,6-11,255.0,Arizona,8193029.0
168,Kyrie Irving,Cleveland Cavaliers,2.0,PG,24.0,6-3,193.0,Duke,16407501.0
169,LeBron James,Cleveland Cavaliers,23.0,SF,31.0,6-8,250.0,NaN,22970500.0
170,Richard Jefferson,Cleveland Cavaliers,24.0,SF,35.0,6-7,233.0,Arizona,947276.0
171,Dahntay Jones,Cleveland Cavaliers,30.0,SG,35.0,6-6,225.0,Duke,NaN
172,James Jones,Cleveland Cavaliers,1.0,SG,35.0,6-8,218.0,Miami (FL),947276.0
173,Sasha Kaun,Cleveland Cavaliers,14.0,C,31.0,6-11,260.0,Kansas,1276000.0
174,Kevin Love,Cleveland Cavaliers,0.0,PF,27.0,6-10,251.0,UCLA,19689000.0
175,Jordan McRae,Cleveland Cavaliers,12.0,SG,25.0,6-5,179.0,Tennessee,111196.0
176,Timofey Mozgov,Cleveland Cavaliers,20.0,C,29.0,7-1,275.0,NaN,4950000.0
177,Iman Shumpert,Cleveland Cavaliers,4.0,SG,25.0,6-5,220.0,Georgia Tech,8988765.0
178,J.R. Smith,Cleveland Cavaliers,5.0,SG,30.0,6-6,225.0,NaN,5000000.0
179,Tristan Thompson,Cleveland Cavaliers,13.0,C,25.0,6-9,238.0,Texas,14260870.0
180,Mo Williams,Cleveland Cavaliers,52.0,PG,33.0,6-1,198.0,Alabama,2100000.0
181,Joel Anthony,Detroit Pistons,50.0,C,33.0,6-9,245.0,UNLV,2500000.0
182,Aron Baynes,Detroit Pistons,12.0,C,29.0,6-10,260.0,Washington State,6500000.0
183,Steve Blake,Detroit Pistons,22.0,PG,36.0,6-3,172.0,Maryland,2170465.0
184,Lorenzo Brown,Detroit Pistons,17.0,PG,25.0,6-5,189.0,North Carolina State,111444.0
185,Reggie Bullock,Detroit Pistons,25.0,SF,25.0,6-7,205.0,North Carolina,1252440.0
186,Kentavious Caldwell-Pope,Detroit Pistons,5.0,SG,23.0,6-5,205.0,Georgia,2891760.0
187,Spencer Dinwiddie,Detroit Pistons,8.0,PG,23.0,6-6,200.0,Colorado,845059.0
188,Andre Drummond,Detroit Pistons,0.0,C,22.0,6-11,279.0,Connecticut,3272091.0
189,Tobias Harris,Detroit Pistons,34.0,SF,23.0,6-9,235.0,Tennessee,16000000.0
190,Darrun Hilliard,Detroit Pistons,6.0,SF,23.0,6-6,205.0,Villanova,600000.0
191,Reggie Jackson,Detroit Pistons,1.0,PG,26.0,6-3,208.0,Boston College,13913044.0
192,Stanley Johnson,Detroit Pistons,3.0,SF,20.0,6-7,245.0,Arizona,2841960.0
193,Jodie Meeks,Detroit Pistons,20.0,SG,28.0,6-4,210.0,Kentucky,6270000.0
194,Marcus Morris,Detroit Pistons,13.0,PF,26.0,6-9,235.0,Kansas,5000000.0
195,Anthony Tolliver,Detroit Pistons,43.0,PF,31.0,6-8,240.0,Creighton,3000000.0
196,Lavoy Allen,Indiana Pacers,5.0,PF,27.0,6-9,255.0,Temple,4050000.0
197,Rakeem Christmas,Indiana Pacers,25.0,PF,24.0,6-9,250.0,Syracuse,1007026.0
198,Monta Ellis,Indiana Pacers,11.0,SG,30.0,6-3,185.0,NaN,10300000.0
199,Paul George,Indiana Pacers,13.0,SF,26.0,6-9,220.0,Fresno State,17120106.0
200,George Hill,Indiana Pacers,3.0,PG,30.0,6-3,188.0,IUPUI,8000000.0
201,Jordan Hill,Indiana Pacers,27.0,C,28.0,6-10,235.0,Arizona,4000000.0
202,Solomon Hill,Indiana Pacers,44.0,SF,25.0,6-7,225.0,Arizona,1358880.0
203,Ty Lawson,Indiana Pacers,10.0,PG,28.0,5-11,195.0,North Carolina,211744.0
204,Ian Mahinmi,Indiana Pacers,28.0,C,29.0,6-11,250.0,NaN,4000000.0
205,C.J. Miles,Indiana Pacers,0.0,SF,29.0,6-6,231.0,NaN,4394225.0
206,Glenn Robinson III,Indiana Pacers,40.0,SG,22.0,6-7,222.0,Michigan,1100000.0
207,Rodney Stuckey,Indiana Pacers,2.0,PG,30.0,6-5,205.0,Eastern Washington,7000000.0
208,Myles Turner,Indiana Pacers,33.0,PF,20.0,6-11,243.0,Texas,2357760.0
209,Shayne Whittington,Indiana Pacers,42.0,PF,25.0,6-11,250.0,Western Michigan,845059.0
210,Joe Young,Indiana Pacers,1.0,PG,23.0,6-2,180.0,Oregon,1007026.0
211,Giannis Antetokounmpo,Milwaukee Bucks,34.0,SF,21.0,6-11,222.0,NaN,1953960.0
212,Jerryd Bayless,Milwaukee Bucks,19.0,PG,27.0,6-3,200.0,Arizona,3000000.0
213,Michael Carter-Williams,Milwaukee Bucks,5.0,PG,24.0,6-6,190.0,Syracuse,2399040.0
214,Jared Cunningham,Milwaukee Bucks,9.0,SG,25.0,6-4,195.0,Oregon State,947276.0
215,Tyler Ennis,Milwaukee Bucks,11.0,PG,21.0,6-3,194.0,Syracuse,1662360.0
216,John Henson,Milwaukee Bucks,31.0,PF,25.0,6-11,229.0,North Carolina,2943221.0
217,Damien Inglis,Milwaukee Bucks,17.0,SF,21.0,6-8,246.0,NaN,855000.0
218,O.J. Mayo,Milwaukee Bucks,3.0,SG,28.0,6-5,210.0,USC,8000000.0
219,Khris Middleton,Milwaukee Bucks,22.0,SG,24.0,6-8,234.0,Texas A&M,14700000.0
220,Greg Monroe,Milwaukee Bucks,15.0,C,26.0,6-11,265.0,Georgetown,16407500.0
221,Steve Novak,Milwaukee Bucks,6.0,SF,32.0,6-10,225.0,Marquette,295327.0
222,Johnny O'Bryant III,Milwaukee Bucks,77.0,PF,23.0,6-9,257.0,LSU,845059.0
223,Jabari Parker,Milwaukee Bucks,12.0,PF,21.0,6-8,250.0,Duke,5152440.0
224,Miles Plumlee,Milwaukee Bucks,18.0,C,27.0,6-11,249.0,Duke,2109294.0
225,Greivis Vasquez,Milwaukee Bucks,21.0,PG,29.0,6-6,217.0,Maryland,6600000.0
226,Rashad Vaughn,Milwaukee Bucks,20.0,SG,19.0,6-6,202.0,UNLV,1733040.0
227,Justin Anderson,Dallas Mavericks,1.0,SG,22.0,6-6,228.0,Virginia,1449000.0
228,J.J. Barea,Dallas Mavericks,5.0,PG,31.0,6-0,185.0,Northeastern,4290000.0
229,Jeremy Evans,Dallas Mavericks,21.0,SF,28.0,6-9,200.0,Western Kentucky,1100602.0
230,Raymond Felton,Dallas Mavericks,2.0,PG,31.0,6-1,205.0,North Carolina,3950313.0
231,Devin Harris,Dallas Mavericks,34.0,PG,33.0,6-3,185.0,Wisconsin,4053446.0
232,David Lee,Dallas Mavericks,42.0,PF,33.0,6-9,245.0,Florida,2085671.0
233,Wesley Matthews,Dallas Mavericks,23.0,SG,29.0,6-5,220.0,Marquette,16407500.0
234,JaVale McGee,Dallas Mavericks,11.0,C,28.0,7-0,270.0,Nevada,1270964.0
235,Salah Mejri,Dallas Mavericks,50.0,C,29.0,7-2,245.0,NaN,525093.0
236,Dirk Nowitzki,Dallas Mavericks,41.0,PF,37.0,7-0,245.0,NaN,8333334.0
237,Zaza Pachulia,Dallas Mavericks,27.0,C,32.0,6-11,275.0,NaN,5200000.0
238,Chandler Parsons,Dallas Mavericks,25.0,SF,27.0,6-10,230.0,Florida,15361500.0
239,Dwight Powell,Dallas Mavericks,7.0,PF,24.0,6-11,240.0,Stanford,845059.0
240,Charlie Villanueva,Dallas Mavericks,3.0,PF,31.0,6-11,232.0,Connecticut,947276.0
241,Deron Williams,Dallas Mavericks,8.0,PG,31.0,6-3,200.0,Illinois,5378974.0
242,Trevor Ariza,Houston Rockets,1.0,SF,30.0,6-8,215.0,UCLA,8193030.0
243,Michael Beasley,Houston Rockets,8.0,SF,27.0,6-10,235.0,Kansas State,306527.0
244,Patrick Beverley,Houston Rockets,2.0,PG,27.0,6-1,185.0,Arkansas,6486486.0
245,Corey Brewer,Houston Rockets,33.0,SG,30.0,6-9,186.0,Florida,8229375.0
246,Clint Capela,Houston Rockets,15.0,PF,22.0,6-10,240.0,NaN,1242720.0
247,Sam Dekker,Houston Rockets,7.0,SF,22.0,6-9,230.0,Wisconsin,1646400.0
248,Andrew Goudelock,Houston Rockets,0.0,PG,27.0,6-3,200.0,Charleston,200600.0
249,James Harden,Houston Rockets,13.0,SG,26.0,6-5,220.0,Arizona State,15756438.0
250,Montrezl Harrell,Houston Rockets,35.0,PF,22.0,6-8,240.0,Louisville,1000000.0
251,Dwight Howard,Houston Rockets,12.0,C,30.0,6-11,265.0,NaN,22359364.0
252,Terrence Jones,Houston Rockets,6.0,PF,24.0,6-9,252.0,Kentucky,2489530.0
253,K.J. McDaniels,Houston Rockets,32.0,SG,23.0,6-6,205.0,Clemson,3189794.0
254,Donatas Motiejunas,Houston Rockets,20.0,PF,25.0,7-0,222.0,NaN,2288205.0
255,Josh Smith,Houston Rockets,5.0,C,30.0,6-9,225.0,NaN,947276.0
256,Jason Terry,Houston Rockets,31.0,SG,38.0,6-2,185.0,Arizona,947276.0
257,Jordan Adams,Memphis Grizzlies,3.0,SG,21.0,6-5,209.0,UCLA,1404600.0
258,Tony Allen,Memphis Grizzlies,9.0,SG,34.0,6-4,213.0,Oklahoma State,5158539.0
259,Chris Andersen,Memphis Grizzlies,7.0,PF,37.0,6-10,245.0,Blinn College,5000000.0
260,Matt Barnes,Memphis Grizzlies,22.0,SF,36.0,6-7,226.0,UCLA,3542500.0
261,Vince Carter,Memphis Grizzlies,15.0,SG,39.0,6-6,220.0,North Carolina,4088019.0
262,Mike Conley,Memphis Grizzlies,11.0,PG,28.0,6-1,175.0,Ohio State,9588426.0

##### Display the first 5 rows.

In [3]:
data.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

##### Check the number of rows and columns.

In [4]:
data.shape

(458, 9)

##### List all column names.

In [34]:
data.columns.values

array(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'], dtype=object)

##### Categorical columns inspection:

In [6]:
data['Team'].unique()

array(['Boston Celtics', 'Brooklyn Nets', 'New York Knicks',
       'Philadelphia 76ers', 'Toronto Raptors', 'Golden State Warriors',
       'Los Angeles Clippers', 'Los Angeles Lakers', 'Phoenix Suns',
       'Sacramento Kings', 'Chicago Bulls', 'Cleveland Cavaliers',
       'Detroit Pistons', 'Indiana Pacers', 'Milwaukee Bucks',
       'Dallas Mavericks', 'Houston Rockets', 'Memphis Grizzlies',
       'New Orleans Pelicans', 'San Antonio Spurs', 'Atlanta Hawks',
       'Charlotte Hornets', 'Miami Heat', 'Orlando Magic',
       'Washington Wizards', 'Denver Nuggets', 'Minnesota Timberwolves',
       'Oklahoma City Thunder', 'Portland Trail Blazers', 'Utah Jazz',
       nan], dtype=object)

In [7]:
data['Position'].unique()  #categorical column

array(['PG', 'SF', 'SG', 'PF', 'C', nan], dtype=object)

In [8]:
data['College'].nunique()  # number of unique colleges

118

In [9]:
data['Height'].unique()

array(['6-2', '6-6', '6-5', '6-10', '6-9', '6-8', '7-0', '6-4', '5-9',
       '6-7', '6-3', '5-11', '6-11', '7-3', '6-0', '7-2', '6-1', '7-1',
       nan], dtype=object)

###  Data Cleaning

In [10]:
data.dtypes

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

##### Count how many missing (NaN) values are in each column.

In [11]:
data.isnull().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

##### Convert the Salary column to numeric (handle errors). 

##### Drop rows where Salary is missing.

An error will be generated while converting the `Salary` column from float to int, because it contains NA values:



IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer: Error while type casting for column 'Salary'

In [12]:
data['Salary'].isnull().sum()

12

In [13]:
data[data['Salary'].isnull()]  #inspecting the rows with no salary

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
46,Elton Brand,Philadelphia 76ers,42.0,PF,37.0,6-9,254.0,Duke,NaN
171,Dahntay Jones,Cleveland Cavaliers,30.0,SG,35.0,6-6,225.0,Duke,NaN
264,Jordan Farmar,Memphis Grizzlies,4.0,PG,29.0,6-2,180.0,UCLA,NaN
269,Ray McCallum,Memphis Grizzlies,5.0,PG,24.0,6-3,190.0,Detroit,NaN
270,Xavier Munford,Memphis Grizzlies,14.0,PG,24.0,6-3,180.0,Rhode Island,NaN
273,Alex Stepheson,Memphis Grizzlies,35.0,PF,28.0,6-10,270.0,USC,NaN
350,Briante Weber,Miami Heat,12.0,PG,23.0,6-2,165.0,Virginia Commonwealth,NaN
353,Dorell Wright,Miami Heat,11.0,SF,30.0,6-9,205.0,NaN,NaN
397,Axel Toupane,Denver Nuggets,6.0,SG,23.0,6-7,210.0,NaN,NaN
409,Greg Smith,Minnesota Timberwolves,4.0,PF,25.0,6-10,250.0,Fresno State,NaN
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

1. Drop the row where all the values are NULL.
2. Drop all the rows where `Salary` is NULL.
3. Convert `Salary` from float to int.
4. Replace NULL values to 'Unknown' in column `College`.

In [14]:
data.dropna(subset= ['Salary'], inplace= True) #

In [15]:
data['Salary'].isnull().sum()

0

In [16]:
data= data.astype({'Salary': int})
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 446 entries, 0 to 456
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      446 non-null    object
 1   Team      446 non-null    object
 2   Number    446 non-null    float64
 3   Position  446 non-null    object
 4   Age       446 non-null    float64
 5   Height    446 non-null    object
 6   Weight    446 non-null    float64
 7   College   364 non-null    object
 8   Salary    446 non-null    int32
dtypes: float64(3), int32(1), object(5)
memory usage: 33.1+ KB

In [17]:
data['College']= data['College'].fillna("Unknown")

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 446 entries, 0 to 456
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      446 non-null    object
 1   Team      446 non-null    object
 2   Number    446 non-null    float64
 3   Position  446 non-null    object
 4   Age       446 non-null    float64
 5   Height    446 non-null    object
 6   Weight    446 non-null    float64
 7   College   446 non-null    object
 8   Salary    446 non-null    int32
dtypes: float64(3), int32(1), object(5)
memory usage: 33.1+ KB

###  Filtering Data

##### Show all players from Boston Celtics.

In [19]:
data.loc[data['Team'] == 'Boston Celtics', ['Name']].reset_index(drop= True)

               Name
0     Avery Bradley
1       Jae Crowder
2       R.J. Hunter
3     Jonas Jerebko
4      Amir Johnson
5     Jordan Mickey
6      Kelly Olynyk
7      Terry Rozier
8      Marcus Smart
9   Jared Sullinger
10    Isaiah Thomas
11      Evan Turner
12      James Young
13     Tyler Zeller

##### Show players whose Age is greater than 30.

In [20]:
data.loc[data['Age'] > 30, ['Name']].reset_index(drop= True)

                  Name
0         Jarrett Jack
1         Lou Amundson
2      Carmelo Anthony
3        Jose Calderon
4        Sasha Vujacic
5          Carl Landry
6           Luis Scola
7      Leandro Barbosa
8         Andrew Bogut
9       Andre Iguodala
10    Anderson Varejao
11      Jamal Crawford
12          Chris Paul
13         Paul Pierce
14      Pablo Prigioni
15           JJ Redick
16        Brandon Bass
17         Kobe Bryant
18     Marcelo Huertas
19   Metta World Peace
20          Nick Young
21      Tyson Chandler
22        Ronnie Price
23         P.J. Tucker
24        Caron Butler
25        Aaron Brooks
26       Mike Dunleavy
27           Pau Gasol
28         Joakim Noah
29       Channing Frye
30        LeBron James
31   Richard Jefferson
32         James Jones
33          Sasha Kaun
34         Mo Williams
35        Joel Anthony
36         Steve Blake
37    Anthony Tolliver
38         Steve Novak
39          J.J. Barea
40      Raymond Felton
41        Devin Harris
42           David Lee
43       Dirk Nowitzki
44       Zaza Pachulia
45  Charlie Villanueva
46      Deron Williams
47         Jason Terry
48          Tony Allen
49      Chris Andersen
50         Matt Barnes
51        Vince Carter
52          Marc Gasol
53       Zach Randolph
54    Kendrick Perkins
55         Matt Bonner
56          Boris Diaw
57          Tim Duncan
58       Manu Ginobili
59        Kevin Martin
60        Andre Miller
61         Tony Parker
62          David West
63        Kirk Hinrich
64      Kris Humphries
65         Kyle Korver
66        Paul Millsap
67     Thabo Sefolosha
68      Tiago Splitter
69        Al Jefferson
70          Chris Bosh
71           Luol Deng
72       Udonis Haslem
73         Joe Johnson
74   Amar'e Stoudemire
75         Dwyane Wade
76         C.J. Watson
77       Alan Anderson
78         Drew Gooden
79       Marcin Gortat
80        Nene Hilario
81         Mike Miller
82       Jameer Nelson
83       Kevin Garnett
84     Tayshaun Prince
85       Nick Collison
86          Randy Foye
87       Nazr Mohammed
88         Chris Kaman

##### Filter players who play as PG (Point Guard).

In [21]:
data[data['Position'] == 'PG']

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0,Miami (FL),1500000
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0,Texas A&M,947276
34,Jose Calderon,New York Knicks,3.0,PG,34.0,6-3,200.0,Unknown,7402812
37,Jerian Grant,New York Knicks,13.0,PG,23.0,6-4,195.0,Notre Dame,1572360
47,Isaiah Canaan,Philadelphia 76ers,0.0,PG,25.0,6-0,201.0,Murray State,947276
53,Kendall Marshall,Philadelphia 76ers,5.0,PG,24.0,6-4,200.0,North Carolina,2144772
54,T.J. McConnell,Philadelphia 76ers,12.0,PG,24.0,6-2,200.0,Arizona,525093
57,Ish Smith,Philadelphia 76ers,1.0,PG,27.0,6-0,175.0,Wake Forest,947276
66,Cory Joseph,Toronto Raptors,6.0,PG,24.0,6-3,190.0,Texas,7000000
67,Kyle Lowry,Toronto Raptors,7.0,PG,30.0,6-0,205.0,Villanova,12000000
75,Delon Wright,Toronto Raptors,55.0,PG,24.0,6-5,190.0,Utah,1509360
80,Stephen Curry,Golden State Warriors,30.0,PG,28.0,6-3,190.0,Davidson,11370786
84,Shaun Livingston,Golden State Warriors,34.0,PG,30.0,6-7,192.0,Unknown,5543725
100,Chris Paul,Los Angeles Clippers,3.0,PG,31.0,6-0,175.0,Wake Forest,21468695
102,Pablo Prigioni,Los Angeles Clippers,9.0,PG,39.0,6-3,185.0,Unknown,947726
104,Austin Rivers,Los Angeles Clippers,25.0,PG,23.0,6-4,200.0,Duke,3110796
110,Jordan Clarkson,Los Angeles Lakers,6.0,PG,24.0,6-5,194.0,Missouri,845059
112,Marcelo Huertas,Los Angeles Lakers,9.0,PG,33.0,6-3,200.0,Unknown,525093
116,D'Angelo Russell,Los Angeles Lakers,1.0,PG,20.0,6-5,195.0,Ohio State,5103120
121,Eric Bledsoe,Phoenix Suns,2.0,PG,26.0,6-1,190.0,Kentucky,13500000
127,Brandon Knight,Phoenix Suns,3.0,PG,24.0,6-3,189.0,Kentucky,13500000
130,Phil Pressey,Phoenix Suns,25.0,PG,25.0,5-11,175.0,Missouri,55722
131,Ronnie Price,Phoenix Suns,14.0,PG,32.0,6-2,190.0,Utah Valley,947276
142,Darren Collison,Sacramento Kings,7.0,PG,28.0,6-0,175.0,UCLA,5013559
150,Rajon Rondo,Sacramento Kings,9.0,PG,30.0,6-1,186.0,Kentucky,9500000
152,Aaron Brooks,Chicago Bulls,0.0,PG,31.0,6-0,161.0,Oregon,2250000
164,Derrick Rose,Chicago Bulls,1.0,PG,27.0,6-3,190.0,Memphis,20093064
166,Matthew Dellavedova,Cleveland Cavaliers,8.0,PG,25.0,6-4,198.0,Saint Mary's,1147276
168,Kyrie Irving,Cleveland Cavaliers,2.0,PG,24.0,6-3,193.0,Duke,16407501
180,Mo Williams,Cleveland Cavaliers,52.0,PG,33.0,6-1,198.0,Alabama,2100000
183,Steve Blake,Detroit Pistons,22.0,PG,36.0,6-3,172.0,Maryland,2170465
184,Lorenzo Brown,Detroit Pistons,17.0,PG,25.0,6-5,189.0,North Carolina State,111444
187,Spencer Dinwiddie,Detroit Pistons,8.0,PG,23.0,6-6,200.0,Colorado,845059
191,Reggie Jackson,Detroit Pistons,1.0,PG,26.0,6-3,208.0,Boston College,13913044
200,George Hill,Indiana Pacers,3.0,PG,30.0,6-3,188.0,IUPUI,8000000
203,Ty Lawson,Indiana Pacers,10.0,PG,28.0,5-11,195.0,North Carolina,211744
207,Rodney Stuckey,Indiana Pacers,2.0,PG,30.0,6-5,205.0,Eastern Washington,7000000
210,Joe Young,Indiana Pacers,1.0,PG,23.0,6-2,180.0,Oregon,1007026
212,Jerryd Bayless,Milwaukee Bucks,19.0,PG,27.0,6-3,200.0,Arizona,3000000
213,Michael Carter-Williams,Milwaukee Bucks,5.0,PG,24.0,6-6,190.0,Syracuse,2399040
215,Tyler Ennis,Milwaukee Bucks,11.0,PG,21.0,6-3,194.0,Syracuse,1662360
225,Greivis Vasquez,Milwaukee Bucks,21.0,PG,29.0,6-6,217.0,Maryland,6600000
228,J.J. Barea,Dallas Mavericks,5.0,PG,31.0,6-0,185.0,Northeastern,4290000
230,Raymond Felton,Dallas Mavericks,2.0,PG,31.0,6-1,205.0,North Carolina,3950313
231,Devin Harris,Dallas Mavericks,34.0,PG,33.0,6-3,185.0,Wisconsin,4053446
241,Deron Williams,Dallas Mavericks,8.0,PG,31.0,6-3,200.0,Illinois,5378974
244,Patrick Beverley,Houston Rockets,2.0,PG,27.0,6-1,185.0,Arkansas,6486486
248,Andrew Goudelock,Houston Rockets,0.0,PG,27.0,6-3,200.0,Charleston,200600
262,Mike Conley,Memphis Grizzlies,11.0,PG,28.0,6-1,175.0,Ohio State,9588426
263,Bryce Cotton,Memphis Grizzlies,8.0,PG,23.0,6-1,165.0,Providence,700902
279,Norris Cole,New Orleans Pelicans,30.0,PG,27.0,6-2,175.0,Cleveland State,3036927
283,Toney Douglas,New Orleans Pelicans,16.0,PG,30.0,6-2,195.0,Florida State,1164858
286,Tim Frazier,New Orleans Pelicans,2.0,PG,25.0,6-1,170.0,Penn State,845059
290,Jrue Holiday,New Orleans Pelicans,11.0,PG,25.0,6-4,205.0,UCLA,10595507
304,Andre Miller,San Antonio Spurs,24.0,PG,40.0,6-3,200.0,Utah,250750
305,Patty Mills,San Antonio Spurs,8.0,PG,27.0,6-0,185.0,Saint Mary's,3578947
306,Tony Parker,San Antonio Spurs,9.0,PG,34.0,6-2,185.0,Unknown,13437500
318,Dennis Schroder,Atlanta Hawks,17.0,PG,22.0,6-1,172.0,Unknown,1763400
323,Jeff Teague,Atlanta Hawks,0.0,PG,27.0,6-2,186.0,Wake Forest,8000000
326,Jorge Gutierrez,Charlotte Hornets,12.0,PG,27.0,6-3,189.0,California,189455
335,Jeremy Lin,Charlotte Hornets,7.0,PG,27.0,6-3,200.0,Harvard,2139000
336,Kemba Walker,Charlotte Hornets,15.0,PG,26.0,6-1,184.0,Connecticut,12000000
341,Goran Dragic,Miami Heat,7.0,PG,30.0,6-3,190.0,Unknown,14783000
359,Brandon Jennings,Orlando Magic,55.0,PG,26.0,6-1,169.0,Unknown,8344497
361,Shabazz Napier,Orlando Magic,13.0,PG,24.0,6-1,175.0,Connecticut,1294440
364,Elfrid Payton,Orlando Magic,4.0,PG,22.0,6-4,185.0,Louisiana-Lafayette,2505720
367,C.J. Watson,Orlando Magic,32.0,PG,32.0,6-2,175.0,Tennessee,5000000
379,Ramon Sessions,Washington Wizards,7.0,PG,30.0,6-3,190.0,Nevada,2170465
382,John Wall,Washington Wizards,2.0,PG,25.0,6-4,195.0,Kentucky,15851950
384,D.J. Augustin,Denver Nuggets,12.0,PG,28.0,6-0,183.0,Texas,3000000
393,Emmanuel Mudiay,Denver Nuggets,0.0,PG,20.0,6-5,200.0,Unknown,3102240
394,Jameer Nelson,Denver Nuggets,1.0,PG,34.0,6-0,190.0,Saint Joseph's,4345000
401,Tyus Jones,Minnesota Timberwolves,1.0,PG,20.0,6-2,195.0,Duke,1282080
402,Zach LaVine,Minnesota Timberwolves,8.0,PG,21.0,6-5,189.0,UCLA,2148360
407,Ricky Rubio,Minnesota Timberwolves,9.0,PG,25.0,6-4,194.0,Unknown,12700000
422,Cameron Payne,Oklahoma City Thunder,22.0,PG,21.0,6-3,185.0,Murray State,2021520
426,Russell Westbrook,Oklahoma City Thunder,0.0,PG,27.0,6-3,200.0,UCLA,16744218
436,Damian Lillard,Portland Trail Blazers,0.0,PG,25.0,6-3,195.0,Weber State,4236287
440,Brian Roberts,Portland Trail Blazers,2.0,PG,30.0,6-1,173.0,Dayton,2854940
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240
445,Dante Exum,Utah Jazz,11.0,PG,20.0,6-6,190.0,Unknown,3777720
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,Unknown,900000

##### Find players with Salary greater than 5,000,000.

In [22]:
data[data['Salary'] > 5000000]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,Unknown,12000000
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955
30,Arron Afflalo,New York Knicks,4.0,SG,30.0,6-5,210.0,UCLA,8000000
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000
34,Jose Calderon,New York Knicks,3.0,PG,34.0,6-3,200.0,Unknown,7402812
38,Robin Lopez,New York Knicks,8.0,C,28.0,7-0,255.0,Stanford,12650000
52,Carl Landry,Philadelphia 76ers,7.0,PF,32.0,6-9,248.0,Purdue,6500000
63,DeMarre Carroll,Toronto Raptors,5.0,SF,29.0,6-8,212.0,Missouri,13600000
64,DeMar DeRozan,Toronto Raptors,10.0,SG,26.0,6-7,220.0,USC,10050000
66,Cory Joseph,Toronto Raptors,6.0,PG,24.0,6-3,190.0,Texas,7000000
67,Kyle Lowry,Toronto Raptors,7.0,PG,30.0,6-0,205.0,Villanova,12000000
69,Patrick Patterson,Toronto Raptors,54.0,PF,27.0,6-9,235.0,Kentucky,6268675
78,Andrew Bogut,Golden State Warriors,12.0,C,31.0,7-0,260.0,Utah,13800000
80,Stephen Curry,Golden State Warriors,30.0,PG,28.0,6-3,190.0,Davidson,11370786
82,Draymond Green,Golden State Warriors,23.0,PF,26.0,6-7,230.0,Michigan State,14260870
83,Andre Iguodala,Golden State Warriors,9.0,SF,32.0,6-6,215.0,Arizona,11710456
84,Shaun Livingston,Golden State Warriors,34.0,PG,30.0,6-7,192.0,Unknown,5543725
89,Klay Thompson,Golden State Warriors,11.0,SG,26.0,6-7,215.0,Washington State,15501000
93,Jamal Crawford,Los Angeles Clippers,11.0,SG,36.0,6-5,195.0,Michigan,5675000
95,Jeff Green,Los Angeles Clippers,8.0,SF,29.0,6-9,235.0,Georgetown,9650000
96,Blake Griffin,Los Angeles Clippers,32.0,PF,27.0,6-10,251.0,Oklahoma,18907726
98,DeAndre Jordan,Los Angeles Clippers,6.0,C,27.0,6-11,265.0,Texas A&M,19689000
100,Chris Paul,Los Angeles Clippers,3.0,PG,31.0,6-0,175.0,Wake Forest,21468695
103,JJ Redick,Los Angeles Clippers,4.0,SG,31.0,6-4,190.0,Duke,7085000
109,Kobe Bryant,Los Angeles Lakers,24.0,SF,37.0,6-6,212.0,Unknown,25000000
111,Roy Hibbert,Los Angeles Lakers,17.0,C,29.0,7-2,270.0,Georgetown,15592217
116,D'Angelo Russell,Los Angeles Lakers,1.0,PG,20.0,6-5,195.0,Ohio State,5103120
118,Louis Williams,Los Angeles Lakers,23.0,SG,29.0,6-1,175.0,Unknown,7000000
120,Nick Young,Los Angeles Lakers,0.0,SF,31.0,6-7,210.0,USC,5219169
121,Eric Bledsoe,Phoenix Suns,2.0,PG,26.0,6-1,190.0,Kentucky,13500000
124,Tyson Chandler,Phoenix Suns,4.0,C,33.0,7-1,240.0,Unknown,13000000
127,Brandon Knight,Phoenix Suns,3.0,PG,24.0,6-3,189.0,Kentucky,13500000
132,Mirza Teletovic,Phoenix Suns,35.0,PF,30.0,6-9,242.0,Unknown,5500000
133,P.J. Tucker,Phoenix Suns,17.0,SF,31.0,6-6,245.0,Texas,5500000
138,Marco Belinelli,Sacramento Kings,3.0,SG,30.0,6-5,210.0,Unknown,6060606
142,Darren Collison,Sacramento Kings,7.0,PG,28.0,6-0,175.0,UCLA,5013559
143,DeMarcus Cousins,Sacramento Kings,15.0,C,25.0,6-11,270.0,Kentucky,15851950
146,Rudy Gay,Sacramento Kings,8.0,SF,29.0,6-8,230.0,Connecticut,12403101
147,Kosta Koufos,Sacramento Kings,41.0,C,27.0,7-0,265.0,Ohio State,7700000
150,Rajon Rondo,Sacramento Kings,9.0,PG,30.0,6-1,186.0,Kentucky,9500000
153,Jimmy Butler,Chicago Bulls,21.0,SG,26.0,6-7,220.0,Marquette,16407500
156,Pau Gasol,Chicago Bulls,16.0,C,35.0,7-0,250.0,Unknown,7448760
157,Taj Gibson,Chicago Bulls,22.0,PF,30.0,6-9,225.0,USC,8500000
160,Nikola Mirotic,Chicago Bulls,44.0,PF,25.0,6-10,220.0,Unknown,5543725
162,Joakim Noah,Chicago Bulls,13.0,C,31.0,6-11,232.0,Florida,13400000
164,Derrick Rose,Chicago Bulls,1.0,PG,27.0,6-3,190.0,Memphis,20093064
167,Channing Frye,Cleveland Cavaliers,9.0,PF,33.0,6-11,255.0,Arizona,8193029
168,Kyrie Irving,Cleveland Cavaliers,2.0,PG,24.0,6-3,193.0,Duke,16407501
169,LeBron James,Cleveland Cavaliers,23.0,SF,31.0,6-8,250.0,Unknown,22970500
174,Kevin Love,Cleveland Cavaliers,0.0,PF,27.0,6-10,251.0,UCLA,19689000
177,Iman Shumpert,Cleveland Cavaliers,4.0,SG,25.0,6-5,220.0,Georgia Tech,8988765
179,Tristan Thompson,Cleveland Cavaliers,13.0,C,25.0,6-9,238.0,Texas,14260870
182,Aron Baynes,Detroit Pistons,12.0,C,29.0,6-10,260.0,Washington State,6500000
189,Tobias Harris,Detroit Pistons,34.0,SF,23.0,6-9,235.0,Tennessee,16000000
191,Reggie Jackson,Detroit Pistons,1.0,PG,26.0,6-3,208.0,Boston College,13913044
193,Jodie Meeks,Detroit Pistons,20.0,SG,28.0,6-4,210.0,Kentucky,6270000
198,Monta Ellis,Indiana Pacers,11.0,SG,30.0,6-3,185.0,Unknown,10300000
199,Paul George,Indiana Pacers,13.0,SF,26.0,6-9,220.0,Fresno State,17120106
200,George Hill,Indiana Pacers,3.0,PG,30.0,6-3,188.0,IUPUI,8000000
207,Rodney Stuckey,Indiana Pacers,2.0,PG,30.0,6-5,205.0,Eastern Washington,7000000
218,O.J. Mayo,Milwaukee Bucks,3.0,SG,28.0,6-5,210.0,USC,8000000
219,Khris Middleton,Milwaukee Bucks,22.0,SG,24.0,6-8,234.0,Texas A&M,14700000
220,Greg Monroe,Milwaukee Bucks,15.0,C,26.0,6-11,265.0,Georgetown,16407500
223,Jabari Parker,Milwaukee Bucks,12.0,PF,21.0,6-8,250.0,Duke,5152440
225,Greivis Vasquez,Milwaukee Bucks,21.0,PG,29.0,6-6,217.0,Maryland,6600000
233,Wesley Matthews,Dallas Mavericks,23.0,SG,29.0,6-5,220.0,Marquette,16407500
236,Dirk Nowitzki,Dallas Mavericks,41.0,PF,37.0,7-0,245.0,Unknown,8333334
237,Zaza Pachulia,Dallas Mavericks,27.0,C,32.0,6-11,275.0,Unknown,5200000
238,Chandler Parsons,Dallas Mavericks,25.0,SF,27.0,6-10,230.0,Florida,15361500
241,Deron Williams,Dallas Mavericks,8.0,PG,31.0,6-3,200.0,Illinois,5378974
242,Trevor Ariza,Houston Rockets,1.0,SF,30.0,6-8,215.0,UCLA,8193030
244,Patrick Beverley,Houston Rockets,2.0,PG,27.0,6-1,185.0,Arkansas,6486486
245,Corey Brewer,Houston Rockets,33.0,SG,30.0,6-9,186.0,Florida,8229375
249,James Harden,Houston Rockets,13.0,SG,26.0,6-5,220.0,Arizona State,15756438
251,Dwight Howard,Houston Rockets,12.0,C,30.0,6-11,265.0,Unknown,22359364
258,Tony Allen,Memphis Grizzlies,9.0,SG,34.0,6-4,213.0,Oklahoma State,5158539
262,Mike Conley,Memphis Grizzlies,11.0,PG,28.0,6-1,175.0,Ohio State,9588426
265,Marc Gasol,Memphis Grizzlies,33.0,C,31.0,7-1,255.0,Unknown,19688000
271,Zach Randolph,Memphis Grizzlies,50.0,PF,34.0,6-9,260.0,Michigan State,9638555
272,Lance Stephenson,Memphis Grizzlies,1.0,SF,25.0,6-5,230.0,Cincinnati,9000000
274,Brandan Wright,Memphis Grizzlies,34.0,PF,28.0,6-10,210.0,North Carolina,5464000
276,Ryan Anderson,New Orleans Pelicans,33.0,PF,28.0,6-10,240.0,California,8500000
277,Omer Asik,New Orleans Pelicans,3.0,C,29.0,7-0,255.0,Unknown,9213483
281,Anthony Davis,New Orleans Pelicans,23.0,PF,23.0,6-10,253.0,Kentucky,7070730
285,Tyreke Evans,New Orleans Pelicans,1.0,SG,26.0,6-6,220.0,Memphis,10734586
288,Eric Gordon,New Orleans Pelicans,10.0,SG,27.0,6-4,215.0,Indiana,15514031
290,Jrue Holiday,New Orleans Pelicans,11.0,PG,25.0,6-4,205.0,UCLA,10595507
294,LaMarcus Aldridge,San Antonio Spurs,12.0,PF,30.0,6-11,240.0,Texas,19689000
297,Boris Diaw,San Antonio Spurs,33.0,C,34.0,6-8,250.0,Unknown,7500000
298,Tim Duncan,San Antonio Spurs,21.0,C,40.0,6-11,250.0,Wake Forest,5250000
300,Danny Green,San Antonio Spurs,14.0,SG,28.0,6-6,215.0,North Carolina,10000000
301,Kawhi Leonard,San Antonio Spurs,2.0,SF,24.0,6-7,230.0,San Diego State,16407500
306,Tony Parker,San Antonio Spurs,9.0,PG,34.0,6-2,185.0,Unknown,13437500
312,Al Horford,Atlanta Hawks,15.0,C,30.0,6-10,245.0,Florida,12000000
314,Kyle Korver,Atlanta Hawks,26.0,SG,35.0,6-7,212.0,Creighton,5746479
315,Paul Millsap,Atlanta Hawks,4.0,PF,31.0,6-8,246.0,Louisiana Tech,18671659
321,Tiago Splitter,Atlanta Hawks,11.0,C,31.0,6-11,245.0,Unknown,9756250
323,Jeff Teague,Atlanta Hawks,0.0,PG,27.0,6-2,186.0,Wake Forest,8000000
324,Nicolas Batum,Charlotte Hornets,5.0,SG,27.0,6-8,200.0,Unknown,13125306
329,Spencer Hawes,Charlotte Hornets,0.0,PF,28.0,7-1,245.0,Washington,6110034
330,Al Jefferson,Charlotte Hornets,25.0,C,31.0,6-10,289.0,Unknown,13500000
332,Michael Kidd-Gilchrist,Charlotte Hornets,14.0,SF,22.0,6-7,232.0,Kentucky,6331404
334,Courtney Lee,Charlotte Hornets,1.0,SG,30.0,6-5,200.0,Western Kentucky,5675000
336,Kemba Walker,Charlotte Hornets,15.0,PG,26.0,6-1,184.0,Connecticut,12000000
337,Marvin Williams,Charlotte Hornets,2.0,PF,29.0,6-9,237.0,North Carolina,7000000
339,Chris Bosh,Miami Heat,1.0,PF,32.0,6-11,235.0,Georgia Tech,22192730
340,Luol Deng,Miami Heat,9.0,SF,31.0,6-9,220.0,Duke,10151612
341,Goran Dragic,Miami Heat,7.0,PG,30.0,6-3,190.0,Unknown,14783000
346,Josh McRoberts,Miami Heat,4.0,PF,29.0,6-10,240.0,Duke,5543725
349,Dwyane Wade,Miami Heat,3.0,SG,34.0,6-4,220.0,Marquette,20000000
358,Ersan Ilyasova,Orlando Magic,7.0,PF,29.0,6-10,235.0,Unknown,7900000
359,Brandon Jennings,Orlando Magic,55.0,PG,26.0,6-1,169.0,Unknown,8344497
363,Victor Oladipo,Orlando Magic,5.0,SG,24.0,6-4,210.0,Indiana,5192520
366,Nikola Vucevic,Orlando Magic,9.0,C,25.0,7-0,260.0,USC,11250000
369,Bradley Beal,Washington Wizards,3.0,SG,22.0,6-5,207.0,Florida,5694674
373,Marcin Gortat,Washington Wizards,13.0,C,32.0,6-11,240.0,Unknown,11217391
375,Nene Hilario,Washington Wizards,42.0,C,33.0,6-11,250.0,Unknown,13000000
376,Markieff Morris,Washington Wizards,5.0,PF,26.0,6-10,245.0,Kansas,8000000
382,John Wall,Washington Wizards,2.0,PG,25.0,6-4,195.0,Kentucky,15851950
386,Wilson Chandler,Denver Nuggets,21.0,SF,29.0,6-8,225.0,DePaul,10449438
387,Kenneth Faried,Denver Nuggets,35.0,PF,26.0,6-8,228.0,Morehead State,11235955
388,Danilo Gallinari,Denver Nuggets,8.0,SF,27.0,6-10,225.0,Unknown,14000000
400,Kevin Garnett,Minnesota Timberwolves,21.0,PF,40.0,6-11,240.0,Unknown,8500000
405,Nikola Pekovic,Minnesota Timberwolves,14.0,C,30.0,6-11,307.0,Unknown,12100000
407,Ricky Rubio,Minnesota Timberwolves,9.0,PG,25.0,6-4,194.0,Unknown,12700000
410,Karl-Anthony Towns,Minnesota Timberwolves,32.0,C,20.0,7-0,244.0,Kentucky,5703600
411,Andrew Wiggins,Minnesota Timberwolves,22.0,SG,21.0,6-8,199.0,Kansas,5758680
414,Kevin Durant,Oklahoma City Thunder,35.0,SF,27.0,6-9,240.0,Texas,20158622
417,Serge Ibaka,Oklahoma City Thunder,9.0,PF,26.0,6-10,245.0,Unknown,12250000
418,Enes Kanter,Oklahoma City Thunder,11.0,C,24.0,6-11,245.0,Kentucky,16407500
425,Dion Waiters,Oklahoma City Thunder,3.0,SG,24.0,6-4,220.0,Syracuse,5138430
426,Russell Westbrook,Oklahoma City Thunder,0.0,PG,27.0,6-3,200.0,UCLA,16744218
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0,North Carolina,6980802
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570

###  Sorting

##### Sort players by Salary (highest first).

In [23]:
data[data['Salary'] > 5000000].sort_values(by= 'Salary', ascending= False)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
109,Kobe Bryant,Los Angeles Lakers,24.0,SF,37.0,6-6,212.0,Unknown,25000000
169,LeBron James,Cleveland Cavaliers,23.0,SF,31.0,6-8,250.0,Unknown,22970500
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000
251,Dwight Howard,Houston Rockets,12.0,C,30.0,6-11,265.0,Unknown,22359364
339,Chris Bosh,Miami Heat,1.0,PF,32.0,6-11,235.0,Georgia Tech,22192730
100,Chris Paul,Los Angeles Clippers,3.0,PG,31.0,6-0,175.0,Wake Forest,21468695
414,Kevin Durant,Oklahoma City Thunder,35.0,SF,27.0,6-9,240.0,Texas,20158622
164,Derrick Rose,Chicago Bulls,1.0,PG,27.0,6-3,190.0,Memphis,20093064
349,Dwyane Wade,Miami Heat,3.0,SG,34.0,6-4,220.0,Marquette,20000000
98,DeAndre Jordan,Los Angeles Clippers,6.0,C,27.0,6-11,265.0,Texas A&M,19689000
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000
294,LaMarcus Aldridge,San Antonio Spurs,12.0,PF,30.0,6-11,240.0,Texas,19689000
174,Kevin Love,Cleveland Cavaliers,0.0,PF,27.0,6-10,251.0,UCLA,19689000
265,Marc Gasol,Memphis Grizzlies,33.0,C,31.0,7-1,255.0,Unknown,19688000
96,Blake Griffin,Los Angeles Clippers,32.0,PF,27.0,6-10,251.0,Oklahoma,18907726
315,Paul Millsap,Atlanta Hawks,4.0,PF,31.0,6-8,246.0,Louisiana Tech,18671659
199,Paul George,Indiana Pacers,13.0,SF,26.0,6-9,220.0,Fresno State,17120106
426,Russell Westbrook,Oklahoma City Thunder,0.0,PG,27.0,6-3,200.0,UCLA,16744218
168,Kyrie Irving,Cleveland Cavaliers,2.0,PG,24.0,6-3,193.0,Duke,16407501
153,Jimmy Butler,Chicago Bulls,21.0,SG,26.0,6-7,220.0,Marquette,16407500
233,Wesley Matthews,Dallas Mavericks,23.0,SG,29.0,6-5,220.0,Marquette,16407500
301,Kawhi Leonard,San Antonio Spurs,2.0,SF,24.0,6-7,230.0,San Diego State,16407500
418,Enes Kanter,Oklahoma City Thunder,11.0,C,24.0,6-11,245.0,Kentucky,16407500
220,Greg Monroe,Milwaukee Bucks,15.0,C,26.0,6-11,265.0,Georgetown,16407500
189,Tobias Harris,Detroit Pistons,34.0,SF,23.0,6-9,235.0,Tennessee,16000000
143,DeMarcus Cousins,Sacramento Kings,15.0,C,25.0,6-11,270.0,Kentucky,15851950
382,John Wall,Washington Wizards,2.0,PG,25.0,6-4,195.0,Kentucky,15851950
249,James Harden,Houston Rockets,13.0,SG,26.0,6-5,220.0,Arizona State,15756438
111,Roy Hibbert,Los Angeles Lakers,17.0,C,29.0,7-2,270.0,Georgetown,15592217
288,Eric Gordon,New Orleans Pelicans,10.0,SG,27.0,6-4,215.0,Indiana,15514031
89,Klay Thompson,Golden State Warriors,11.0,SG,26.0,6-7,215.0,Washington State,15501000
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570
238,Chandler Parsons,Dallas Mavericks,25.0,SF,27.0,6-10,230.0,Florida,15361500
341,Goran Dragic,Miami Heat,7.0,PG,30.0,6-3,190.0,Unknown,14783000
219,Khris Middleton,Milwaukee Bucks,22.0,SG,24.0,6-8,234.0,Texas A&M,14700000
82,Draymond Green,Golden State Warriors,23.0,PF,26.0,6-7,230.0,Michigan State,14260870
179,Tristan Thompson,Cleveland Cavaliers,13.0,C,25.0,6-9,238.0,Texas,14260870
388,Danilo Gallinari,Denver Nuggets,8.0,SF,27.0,6-10,225.0,Unknown,14000000
191,Reggie Jackson,Detroit Pistons,1.0,PG,26.0,6-3,208.0,Boston College,13913044
78,Andrew Bogut,Golden State Warriors,12.0,C,31.0,7-0,260.0,Utah,13800000
63,DeMarre Carroll,Toronto Raptors,5.0,SF,29.0,6-8,212.0,Missouri,13600000
121,Eric Bledsoe,Phoenix Suns,2.0,PG,26.0,6-1,190.0,Kentucky,13500000
127,Brandon Knight,Phoenix Suns,3.0,PG,24.0,6-3,189.0,Kentucky,13500000
330,Al Jefferson,Charlotte Hornets,25.0,C,31.0,6-10,289.0,Unknown,13500000
306,Tony Parker,San Antonio Spurs,9.0,PG,34.0,6-2,185.0,Unknown,13437500
162,Joakim Noah,Chicago Bulls,13.0,C,31.0,6-11,232.0,Florida,13400000
324,Nicolas Batum,Charlotte Hornets,5.0,SG,27.0,6-8,200.0,Unknown,13125306
124,Tyson Chandler,Phoenix Suns,4.0,C,33.0,7-1,240.0,Unknown,13000000
375,Nene Hilario,Washington Wizards,42.0,C,33.0,6-11,250.0,Unknown,13000000
407,Ricky Rubio,Minnesota Timberwolves,9.0,PG,25.0,6-4,194.0,Unknown,12700000
38,Robin Lopez,New York Knicks,8.0,C,28.0,7-0,255.0,Stanford,12650000
146,Rudy Gay,Sacramento Kings,8.0,SF,29.0,6-8,230.0,Connecticut,12403101
417,Serge Ibaka,Oklahoma City Thunder,9.0,PF,26.0,6-10,245.0,Unknown,12250000
405,Nikola Pekovic,Minnesota Timberwolves,14.0,C,30.0,6-11,307.0,Unknown,12100000
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,Unknown,12000000
67,Kyle Lowry,Toronto Raptors,7.0,PG,30.0,6-0,205.0,Villanova,12000000
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000
336,Kemba Walker,Charlotte Hornets,15.0,PG,26.0,6-1,184.0,Connecticut,12000000
312,Al Horford,Atlanta Hawks,15.0,C,30.0,6-10,245.0,Florida,12000000
83,Andre Iguodala,Golden State Warriors,9.0,SF,32.0,6-6,215.0,Arizona,11710456
80,Stephen Curry,Golden State Warriors,30.0,PG,28.0,6-3,190.0,Davidson,11370786
366,Nikola Vucevic,Orlando Magic,9.0,C,25.0,7-0,260.0,USC,11250000
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955
387,Kenneth Faried,Denver Nuggets,35.0,PF,26.0,6-8,228.0,Morehead State,11235955
373,Marcin Gortat,Washington Wizards,13.0,C,32.0,6-11,240.0,Unknown,11217391
285,Tyreke Evans,New Orleans Pelicans,1.0,SG,26.0,6-6,220.0,Memphis,10734586
290,Jrue Holiday,New Orleans Pelicans,11.0,PG,25.0,6-4,205.0,UCLA,10595507
386,Wilson Chandler,Denver Nuggets,21.0,SF,29.0,6-8,225.0,DePaul,10449438
198,Monta Ellis,Indiana Pacers,11.0,SG,30.0,6-3,185.0,Unknown,10300000
340,Luol Deng,Miami Heat,9.0,SF,31.0,6-9,220.0,Duke,10151612
64,DeMar DeRozan,Toronto Raptors,10.0,SG,26.0,6-7,220.0,USC,10050000
300,Danny Green,San Antonio Spurs,14.0,SG,28.0,6-6,215.0,North Carolina,10000000
321,Tiago Splitter,Atlanta Hawks,11.0,C,31.0,6-11,245.0,Unknown,9756250
95,Jeff Green,Los Angeles Clippers,8.0,SF,29.0,6-9,235.0,Georgetown,9650000
271,Zach Randolph,Memphis Grizzlies,50.0,PF,34.0,6-9,260.0,Michigan State,9638555
262,Mike Conley,Memphis Grizzlies,11.0,PG,28.0,6-1,175.0,Ohio State,9588426
150,Rajon Rondo,Sacramento Kings,9.0,PG,30.0,6-1,186.0,Kentucky,9500000
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484
277,Omer Asik,New Orleans Pelicans,3.0,C,29.0,7-0,255.0,Unknown,9213483
272,Lance Stephenson,Memphis Grizzlies,1.0,SF,25.0,6-5,230.0,Cincinnati,9000000
177,Iman Shumpert,Cleveland Cavaliers,4.0,SG,25.0,6-5,220.0,Georgia Tech,8988765
400,Kevin Garnett,Minnesota Timberwolves,21.0,PF,40.0,6-11,240.0,Unknown,8500000
276,Ryan Anderson,New Orleans Pelicans,33.0,PF,28.0,6-10,240.0,California,8500000
157,Taj Gibson,Chicago Bulls,22.0,PF,30.0,6-9,225.0,USC,8500000
359,Brandon Jennings,Orlando Magic,55.0,PG,26.0,6-1,169.0,Unknown,8344497
236,Dirk Nowitzki,Dallas Mavericks,41.0,PF,37.0,7-0,245.0,Unknown,8333334
245,Corey Brewer,Houston Rockets,33.0,SG,30.0,6-9,186.0,Florida,8229375
242,Trevor Ariza,Houston Rockets,1.0,SF,30.0,6-8,215.0,UCLA,8193030
167,Channing Frye,Cleveland Cavaliers,9.0,PF,33.0,6-11,255.0,Arizona,8193029
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895
218,O.J. Mayo,Milwaukee Bucks,3.0,SG,28.0,6-5,210.0,USC,8000000
323,Jeff Teague,Atlanta Hawks,0.0,PG,27.0,6-2,186.0,Wake Forest,8000000
376,Markieff Morris,Washington Wizards,5.0,PF,26.0,6-10,245.0,Kansas,8000000
30,Arron Afflalo,New York Knicks,4.0,SG,30.0,6-5,210.0,UCLA,8000000
200,George Hill,Indiana Pacers,3.0,PG,30.0,6-3,188.0,IUPUI,8000000
358,Ersan Ilyasova,Orlando Magic,7.0,PF,29.0,6-10,235.0,Unknown,7900000
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337
147,Kosta Koufos,Sacramento Kings,41.0,C,27.0,7-0,265.0,Ohio State,7700000
297,Boris Diaw,San Antonio Spurs,33.0,C,34.0,6-8,250.0,Unknown,7500000
156,Pau Gasol,Chicago Bulls,16.0,C,35.0,7-0,250.0,Unknown,7448760
34,Jose Calderon,New York Knicks,3.0,PG,34.0,6-3,200.0,Unknown,7402812
103,JJ Redick,Los Angeles Clippers,4.0,SG,31.0,6-4,190.0,Duke,7085000
281,Anthony Davis,New Orleans Pelicans,23.0,PF,23.0,6-10,253.0,Kentucky,7070730
207,Rodney Stuckey,Indiana Pacers,2.0,PG,30.0,6-5,205.0,Eastern Washington,7000000
118,Louis Williams,Los Angeles Lakers,23.0,SG,29.0,6-1,175.0,Unknown,7000000
337,Marvin Williams,Charlotte Hornets,2.0,PF,29.0,6-9,237.0,North Carolina,7000000
66,Cory Joseph,Toronto Raptors,6.0,PG,24.0,6-3,190.0,Texas,7000000
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0,North Carolina,6980802
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117
225,Greivis Vasquez,Milwaukee Bucks,21.0,PG,29.0,6-6,217.0,Maryland,6600000
52,Carl Landry,Philadelphia 76ers,7.0,PF,32.0,6-9,248.0,Purdue,6500000
182,Aron Baynes,Detroit Pistons,12.0,C,29.0,6-10,260.0,Washington State,6500000
244,Patrick Beverley,Houston Rockets,2.0,PG,27.0,6-1,185.0,Arkansas,6486486
332,Michael Kidd-Gilchrist,Charlotte Hornets,14.0,SF,22.0,6-7,232.0,Kentucky,6331404
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000
193,Jodie Meeks,Detroit Pistons,20.0,SG,28.0,6-4,210.0,Kentucky,6270000
69,Patrick Patterson,Toronto Raptors,54.0,PF,27.0,6-9,235.0,Kentucky,6268675
329,Spencer Hawes,Charlotte Hornets,0.0,PF,28.0,7-1,245.0,Washington,6110034
138,Marco Belinelli,Sacramento Kings,3.0,SG,30.0,6-5,210.0,Unknown,6060606
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000
411,Andrew Wiggins,Minnesota Timberwolves,22.0,SG,21.0,6-8,199.0,Kansas,5758680
314,Kyle Korver,Atlanta Hawks,26.0,SG,35.0,6-7,212.0,Creighton,5746479
410,Karl-Anthony Towns,Minnesota Timberwolves,32.0,C,20.0,7-0,244.0,Kentucky,5703600
369,Bradley Beal,Washington Wizards,3.0,SG,22.0,6-5,207.0,Florida,5694674
334,Courtney Lee,Charlotte Hornets,1.0,SG,30.0,6-5,200.0,Western Kentucky,5675000
93,Jamal Crawford,Los Angeles Clippers,11.0,SG,36.0,6-5,195.0,Michigan,5675000
84,Shaun Livingston,Golden State Warriors,34.0,PG,30.0,6-7,192.0,Unknown,5543725
346,Josh McRoberts,Miami Heat,4.0,PF,29.0,6-10,240.0,Duke,5543725
160,Nikola Mirotic,Chicago Bulls,44.0,PF,25.0,6-10,220.0,Unknown,5543725
132,Mirza Teletovic,Phoenix Suns,35.0,PF,30.0,6-9,242.0,Unknown,5500000
133,P.J. Tucker,Phoenix Suns,17.0,SF,31.0,6-6,245.0,Texas,5500000
274,Brandan Wright,Memphis Grizzlies,34.0,PF,28.0,6-10,210.0,North Carolina,5464000
241,Deron Williams,Dallas Mavericks,8.0,PG,31.0,6-3,200.0,Illinois,5378974
298,Tim Duncan,San Antonio Spurs,21.0,C,40.0,6-11,250.0,Wake Forest,5250000
120,Nick Young,Los Angeles Lakers,0.0,SF,31.0,6-7,210.0,USC,5219169
237,Zaza Pachulia,Dallas Mavericks,27.0,C,32.0,6-11,275.0,Unknown,5200000
363,Victor Oladipo,Orlando Magic,5.0,SG,24.0,6-4,210.0,Indiana,5192520
258,Tony Allen,Memphis Grizzlies,9.0,SG,34.0,6-4,213.0,Oklahoma State,5158539
223,Jabari Parker,Milwaukee Bucks,12.0,PF,21.0,6-8,250.0,Duke,5152440
425,Dion Waiters,Oklahoma City Thunder,3.0,SG,24.0,6-4,220.0,Syracuse,5138430
116,D'Angelo Russell,Los Angeles Lakers,1.0,PG,20.0,6-5,195.0,Ohio State,5103120
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000
142,Darren Collison,Sacramento Kings,7.0,PG,28.0,6-0,175.0,UCLA,5013559

##### Sort players by Age (youngest first).

In [24]:
data.loc[:, ['Name', 'Team', 'Age']].sort_values(by= 'Age')

                         Name                    Team   Age
122              Devin Booker            Phoenix Suns  19.0
226             Rashad Vaughn         Milwaukee Bucks  19.0
192           Stanley Johnson         Detroit Pistons  20.0
393           Emmanuel Mudiay          Denver Nuggets  20.0
56              Jahlil Okafor      Philadelphia 76ers  20.0
427           Cliff Alexander  Portland Trail Blazers  20.0
60             Christian Wood      Philadelphia 76ers  20.0
356              Aaron Gordon           Orlando Magic  20.0
13                James Young          Boston Celtics  20.0
62              Bruno Caboclo         Toronto Raptors  20.0
452                Trey Lyles               Utah Jazz  20.0
377           Kelly Oubre Jr.      Washington Wizards  20.0
40         Kristaps Porzingis         New York Knicks  20.0
410        Karl-Anthony Towns  Minnesota Timberwolves  20.0
441               Noah Vonleh  Portland Trail Blazers  20.0
208              Myles Turner          Indiana Pacers  20.0
401                Tyus Jones  Minnesota Timberwolves  20.0
352           Justise Winslow              Miami Heat  20.0
85               Kevon Looney   Golden State Warriors  20.0
116          D'Angelo Russell      Los Angeles Lakers  20.0
445                Dante Exum               Utah Jazz  20.0
422             Cameron Payne   Oklahoma City Thunder  21.0
115             Julius Randle      Los Angeles Lakers  21.0
257              Jordan Adams       Memphis Grizzlies  21.0
215               Tyler Ennis         Milwaukee Bucks  21.0
411            Andrew Wiggins  Minnesota Timberwolves  21.0
389               Gary Harris          Denver Nuggets  21.0
402               Zach LaVine  Minnesota Timberwolves  21.0
163              Bobby Portis           Chicago Bulls  21.0
390              Nikola Jokic          Denver Nuggets  21.0
223             Jabari Parker         Milwaukee Bucks  21.0
125            Archie Goodwin            Phoenix Suns  21.0
357             Mario Hezonja           Orlando Magic  21.0
395              Jusuf Nurkic          Denver Nuggets  21.0
211     Giannis Antetokounmpo         Milwaukee Bucks  21.0
18    Rondae Hollis-Jefferson           Brooklyn Nets  21.0
24           Chris McCullough           Brooklyn Nets  21.0
328            Aaron Harrison       Charlotte Hornets  21.0
6               Jordan Mickey          Boston Celtics  21.0
217             Damien Inglis         Milwaukee Bucks  21.0
250          Montrezl Harrell         Houston Rockets  22.0
247                Sam Dekker         Houston Rockets  22.0
246              Clint Capela         Houston Rockets  22.0
8                Terry Rozier          Boston Celtics  22.0
58               Nik Stauskas      Philadelphia 76ers  22.0
9                Marcus Smart          Boston Celtics  22.0
412              Steven Adams   Oklahoma City Thunder  22.0
295             Kyle Anderson       San Antonio Spurs  22.0
188            Andre Drummond         Detroit Pistons  22.0
369              Bradley Beal      Washington Wizards  22.0
364             Elfrid Payton           Orlando Magic  22.0
3                 R.J. Hunter          Boston Celtics  22.0
227           Justin Anderson        Dallas Mavericks  22.0
318           Dennis Schroder           Atlanta Hawks  22.0
347           Josh Richardson              Miami Heat  22.0
55               Nerlens Noel      Philadelphia 76ers  22.0
206        Glenn Robinson III          Indiana Pacers  22.0
128                  Alex Len            Phoenix Suns  22.0
134               T.J. Warren            Phoenix Suns  22.0
332    Michael Kidd-Gilchrist       Charlotte Hornets  22.0
141       Willie Cauley-Stein        Sacramento Kings  22.0
49                Joel Embiid      Philadelphia 76ers  22.0
50               Jerami Grant      Philadelphia 76ers  22.0
20             Sergey Karasev           Brooklyn Nets  22.0
268             Jarell Martin       Memphis Grizzlies  22.0
51             Richaun Holmes      Philadelphia 76ers  22.0
282        Bryce Dejean-Jones    New Orleans Pelicans  23.0
360              Devyn Marble           Orlando Magic  23.0
253            K.J. McDaniels         Houston Rockets  23.0
155         Cristiano Felicio           Chicago Bulls  23.0
338               Cody Zeller       Charlotte Hornets  23.0
148              Ben McLemore        Sacramento Kings  23.0
355             Evan Fournier           Orlando Magic  23.0
135             Alan Williams            Phoenix Suns  23.0
190           Darrun Hilliard         Detroit Pistons  23.0
187         Spencer Dinwiddie         Detroit Pistons  23.0
189             Tobias Harris         Detroit Pistons  23.0
331        Frank Kaminsky III       Charlotte Hornets  23.0
267             P.J. Hairston       Memphis Grizzlies  23.0
378           Otto Porter Jr.      Washington Wizards  23.0
281             Anthony Davis    New Orleans Pelicans  23.0
114           Larry Nance Jr.      Los Angeles Lakers  23.0
186  Kentavious Caldwell-Pope         Detroit Pistons  23.0
104             Austin Rivers    Los Angeles Clippers  23.0
94             Branden Dawson    Los Angeles Clippers  23.0
263              Bryce Cotton       Memphis Grizzlies  23.0
108             Anthony Brown      Los Angeles Lakers  23.0
32     Thanasis Antetokounmpo         New York Knicks  23.0
432          Maurice Harkless  Portland Trail Blazers  23.0
37               Jerian Grant         New York Knicks  23.0
429           Pat Connaughton  Portland Trail Blazers  23.0
222       Johnny O'Bryant III         Milwaukee Bucks  23.0
438              Luis Montero  Portland Trail Blazers  23.0
45                Tony Wroten         New York Knicks  23.0
443                Trey Burke               Utah Jazz  23.0
22               Shane Larkin           Brooklyn Nets  23.0
447               Rudy Gobert               Utah Jazz  23.0
61            Bismack Biyombo         Toronto Raptors  23.0
210                 Joe Young          Indiana Pacers  23.0
86       James Michael McAdoo   Golden State Warriors  23.0
396            JaKarr Sampson          Denver Nuggets  23.0
403          Shabazz Muhammad  Minnesota Timberwolves  23.0
68             Lucas Nogueira         Toronto Raptors  23.0
70              Norman Powell         Toronto Raptors  23.0
449               Rodney Hood               Utah Jazz  23.0
316              Mike Muscala           Atlanta Hawks  24.0
345             Tyler Johnson              Miami Heat  24.0
437             C.J. McCollum  Portland Trail Blazers  24.0
333               Jeremy Lamb       Charlotte Hornets  24.0
168              Kyrie Irving     Cleveland Cavaliers  24.0
159            Doug McDermott           Chicago Bulls  24.0
454                 Raul Neto               Utah Jazz  24.0
301             Kawhi Leonard       San Antonio Spurs  24.0
444                Alec Burks               Utah Jazz  24.0
325              Troy Daniels       Charlotte Hornets  24.0
446            Derrick Favors               Utah Jazz  24.0
322            Walter Tavares           Atlanta Hawks  24.0
10            Jared Sullinger          Boston Celtics  24.0
219           Khris Middleton         Milwaukee Bucks  24.0
16               Markel Brown           Brooklyn Nets  24.0
317           Lamar Patterson           Atlanta Hawks  24.0
310          Tim Hardaway Jr.           Atlanta Hawks  24.0
149             Eric Moreland        Sacramento Kings  24.0
213   Michael Carter-Williams         Milwaukee Bucks  24.0
145                Duje Dukan        Sacramento Kings  24.0
391         Joffrey Lauvergne          Denver Nuggets  24.0
435            Meyers Leonard  Portland Trail Blazers  24.0
252            Terrence Jones         Houston Rockets  24.0
77            Harrison Barnes   Golden State Warriors  24.0
75               Delon Wright         Toronto Raptors  24.0
74          Jonas Valanciunas         Toronto Raptors  24.0
197          Rakeem Christmas          Indiana Pacers  24.0
371              Jarell Eddie      Washington Wizards  24.0
416              Josh Huestis   Oklahoma City Thunder  24.0
66                Cory Joseph         Toronto Raptors  24.0
239             Dwight Powell        Dallas Mavericks  24.0
363            Victor Oladipo           Orlando Magic  24.0
418               Enes Kanter   Oklahoma City Thunder  24.0
419              Mitch McGary   Oklahoma City Thunder  24.0
127            Brandon Knight            Phoenix Suns  24.0
107               Tarik Black      Los Angeles Lakers  24.0
165                Tony Snell           Chicago Bulls  24.0
425              Dion Waiters   Oklahoma City Thunder  24.0
110           Jordan Clarkson      Los Angeles Lakers  24.0
54             T.J. McConnell      Philadelphia 76ers  24.0
53           Kendall Marshall      Philadelphia 76ers  24.0
423            Andre Roberson   Oklahoma City Thunder  24.0
36          Langston Galloway         New York Knicks  24.0
361            Shabazz Napier           Orlando Magic  24.0
430              Allen Crabbe  Portland Trail Blazers  24.0
166       Matthew Dellavedova     Cleveland Cavaliers  25.0
284               James Ennis    New Orleans Pelicans  25.0
179          Tristan Thompson     Cleveland Cavaliers  25.0
214          Jared Cunningham         Milwaukee Bucks  25.0
175              Jordan McRae     Cleveland Cavaliers  25.0
254        Donatas Motiejunas         Houston Rockets  25.0
272          Lance Stephenson       Memphis Grizzlies  25.0
209        Shayne Whittington          Indiana Pacers  25.0
177             Iman Shumpert     Cleveland Cavaliers  25.0
202              Solomon Hill          Indiana Pacers  25.0
184             Lorenzo Brown         Detroit Pistons  25.0
266            JaMychal Green       Memphis Grizzlies  25.0
185            Reggie Bullock         Detroit Pistons  25.0
0               Avery Bradley          Boston Celtics  25.0
286               Tim Frazier    New Orleans Pelicans  25.0
382                 John Wall      Washington Wizards  25.0
385               Will Barton          Denver Nuggets  25.0
79                  Ian Clark   Golden State Warriors  25.0
404             Adreian Payne  Minnesota Timberwolves  25.0
407               Ricky Rubio  Minnesota Timberwolves  25.0
71              Terrence Ross         Toronto Raptors  25.0
59            Hollis Thompson      Philadelphia 76ers  25.0
366            Nikola Vucevic           Orlando Magic  25.0
48           Robert Covington      Philadelphia 76ers  25.0
44           Derrick Williams         New York Knicks  25.0
428           Al-Farouq Aminu  Portland Trail Blazers  25.0
35           Cleanthony Early         New York Knicks  25.0
436            Damian Lillard  Portland Trail Blazers  25.0
26            Thomas Robinson           Brooklyn Nets  25.0
7                Kelly Olynyk          Boston Celtics  25.0
1                 Jae Crowder          Boston Celtics  25.0
47              Isaiah Canaan      Philadelphia 76ers  25.0
105               C.J. Wilcox    Los Angeles Clippers  25.0
216               John Henson         Milwaukee Bucks  25.0
126              John Jenkins            Phoenix Suns  25.0
289           Jordan Hamilton    New Orleans Pelicans  25.0
113                Ryan Kelly      Los Angeles Lakers  25.0
144                Seth Curry        Sacramento Kings  25.0
160            Nikola Mirotic           Chicago Bulls  25.0
143          DeMarcus Cousins        Sacramento Kings  25.0
290              Jrue Holiday    New Orleans Pelicans  25.0
151          Cameron Bairstow           Chicago Bulls  25.0
130              Phil Pressey            Phoenix Suns  25.0
136                Quincy Acy        Sacramento Kings  25.0
278              Luke Babbitt    New Orleans Pelicans  26.0
359          Brandon Jennings           Orlando Magic  26.0
439             Mason Plumlee  Portland Trail Blazers  26.0
448            Gordon Hayward               Utah Jazz  26.0
451             Chris Johnson               Utah Jazz  26.0
453              Shelvin Mack               Utah Jazz  26.0
307          Jonathon Simmons       San Antonio Spurs  26.0
220               Greg Monroe         Milwaukee Bucks  26.0
455              Tibor Pleiss               Utah Jazz  26.0
362          Andrew Nicholson           Orlando Magic  26.0
417               Serge Ibaka   Oklahoma City Thunder  26.0
336              Kemba Walker       Charlotte Hornets  26.0
249              James Harden         Houston Rockets  26.0
351          Hassan Whiteside              Miami Heat  26.0
399              Gorgui Dieng  Minnesota Timberwolves  26.0
285              Tyreke Evans    New Orleans Pelicans  26.0
354            Dewayne Dedmon           Orlando Magic  26.0
376           Markieff Morris      Washington Wizards  26.0
309             Kent Bazemore           Atlanta Hawks  26.0
387            Kenneth Faried          Denver Nuggets  26.0
456               Jeff Withey               Utah Jazz  26.0
41             Kevin Seraphin         New York Knicks  26.0
25                Willie Reed           Brooklyn Nets  26.0
194             Marcus Morris         Detroit Pistons  26.0
21            Sean Kilpatrick           Brooklyn Nets  26.0
81               Festus Ezeli   Golden State Warriors  26.0
64              DeMar DeRozan         Toronto Raptors  26.0
82             Draymond Green   Golden State Warriors  26.0
14               Tyler Zeller          Boston Celtics  26.0
153              Jimmy Butler           Chicago Bulls  26.0
199               Paul George          Indiana Pacers  26.0
121              Eric Bledsoe            Phoenix Suns  26.0
89              Klay Thompson   Golden State Warriors  26.0
39               Kyle O'Quinn         New York Knicks  26.0
191            Reggie Jackson         Detroit Pistons  26.0
27                 Henry Sims           Brooklyn Nets  26.0
302          Boban Marjanovic       San Antonio Spurs  27.0
426         Russell Westbrook   Oklahoma City Thunder  27.0
117              Robert Sacre      Los Angeles Lakers  27.0
374                JJ Hickson      Washington Wizards  27.0
57                  Ish Smith      Philadelphia 76ers  27.0
174                Kevin Love     Cleveland Cavaliers  27.0
69          Patrick Patterson         Toronto Raptors  27.0
96              Blake Griffin    Los Angeles Clippers  27.0
323               Jeff Teague           Atlanta Hawks  27.0
291           Orlando Johnson    New Orleans Pelicans  27.0
158            Justin Holiday           Chicago Bulls  27.0
161             E'Twaun Moore           Chicago Bulls  27.0
288               Eric Gordon    New Orleans Pelicans  27.0
279               Norris Cole    New Orleans Pelicans  27.0
91               Cole Aldrich    Los Angeles Clippers  27.0
388          Danilo Gallinari          Denver Nuggets  27.0
414              Kevin Durant   Oklahoma City Thunder  27.0
98             DeAndre Jordan    Los Angeles Clippers  27.0
248          Andrew Goudelock         Houston Rockets  27.0
164              Derrick Rose           Chicago Bulls  27.0
140               Omri Casspi        Sacramento Kings  27.0
326           Jorge Gutierrez       Charlotte Hornets  27.0
12                Evan Turner          Boston Celtics  27.0
15           Bojan Bogdanovic           Brooklyn Nets  27.0
137            James Anderson        Sacramento Kings  27.0
305               Patty Mills       San Antonio Spurs  27.0
335                Jeremy Lin       Charlotte Hornets  27.0
11              Isaiah Thomas          Boston Celtics  27.0
224             Miles Plumlee         Milwaukee Bucks  27.0
212            Jerryd Bayless         Milwaukee Bucks  27.0
238          Chandler Parsons        Dallas Mavericks  27.0
29             Thaddeus Young           Brooklyn Nets  27.0
324             Nicolas Batum       Charlotte Hornets  27.0
319                Mike Scott           Atlanta Hawks  27.0
431                  Ed Davis  Portland Trail Blazers  27.0
243           Michael Beasley         Houston Rockets  27.0
244          Patrick Beverley         Houston Rockets  27.0
196               Lavoy Allen          Indiana Pacers  27.0
129                 Jon Leuer            Phoenix Suns  27.0
147              Kosta Koufos        Sacramento Kings  27.0
293          Quincy Pondexter    New Orleans Pelicans  28.0
329             Spencer Hawes       Charlotte Hornets  28.0
97             Wesley Johnson    Los Angeles Clippers  28.0
123            Chase Budinger            Phoenix Suns  28.0
300               Danny Green       San Antonio Spurs  28.0
383            Darrell Arthur          Denver Nuggets  28.0
384             D.J. Augustin          Denver Nuggets  28.0
218                 O.J. Mayo         Milwaukee Bucks  28.0
42               Lance Thomas         New York Knicks  28.0
203                 Ty Lawson          Indiana Pacers  28.0
201               Jordan Hill          Indiana Pacers  28.0
450                Joe Ingles               Utah Jazz  28.0
229              Jeremy Evans        Dallas Mavericks  28.0
17            Wayne Ellington           Brooklyn Nets  28.0
23                Brook Lopez           Brooklyn Nets  28.0
234              JaVale McGee        Dallas Mavericks  28.0
442             Trevor Booker               Utah Jazz  28.0
28               Donald Sloan           Brooklyn Nets  28.0
433          Gerald Henderson  Portland Trail Blazers  28.0
38                Robin Lopez         New York Knicks  28.0
193               Jodie Meeks         Detroit Pistons  28.0
424              Kyle Singler   Oklahoma City Thunder  28.0
142           Darren Collison        Sacramento Kings  28.0
80              Stephen Curry   Golden State Warriors  28.0
88          Marreese Speights   Golden State Warriors  28.0
276             Ryan Anderson    New Orleans Pelicans  28.0
262               Mike Conley       Memphis Grizzlies  28.0
275             Alexis Ajinca    New Orleans Pelicans  28.0
274            Brandan Wright       Memphis Grizzlies  28.0
398           Nemanja Bjelica  Minnesota Timberwolves  28.0
4               Jonas Jerebko          Boston Celtics  29.0
5                Amir Johnson          Boston Celtics  29.0
95                 Jeff Green    Los Angeles Clippers  29.0
381           Marcus Thornton      Washington Wizards  29.0
63            DeMarre Carroll         Toronto Raptors  29.0
408              Damjan Rudez  Minnesota Timberwolves  29.0
346            Josh McRoberts              Miami Heat  29.0
73             Jason Thompson         Toronto Raptors  29.0
65              James Johnson         Toronto Raptors  29.0
118            Louis Williams      Los Angeles Lakers  29.0
386           Wilson Chandler          Denver Nuggets  29.0
99   Luc Richard Mbah a Moute    Los Angeles Clippers  29.0
358            Ersan Ilyasova           Orlando Magic  29.0
111               Roy Hibbert      Los Angeles Lakers  29.0
92                 Jeff Ayres    Los Angeles Clippers  29.0
337           Marvin Williams       Charlotte Hornets  29.0
280          Dante Cunningham    New Orleans Pelicans  29.0
205                C.J. Miles          Indiana Pacers  29.0
204               Ian Mahinmi          Indiana Pacers  29.0
233           Wesley Matthews        Dallas Mavericks  29.0
235               Salah Mejri        Dallas Mavericks  29.0
182               Aron Baynes         Detroit Pistons  29.0
176            Timofey Mozgov     Cleveland Cavaliers  29.0
277                 Omer Asik    New Orleans Pelicans  29.0
287                Alonzo Gee    New Orleans Pelicans  29.0
225           Greivis Vasquez         Milwaukee Bucks  29.0
146                  Rudy Gay        Sacramento Kings  29.0
365               Jason Smith           Orlando Magic  30.0
242              Trevor Ariza         Houston Rockets  30.0
245              Corey Brewer         Houston Rockets  30.0
251             Dwight Howard         Houston Rockets  30.0
370              Jared Dudley      Washington Wizards  30.0

###    GroupBy Operations

##### Find the average salary per team.

In [38]:
(data.groupby('Team')['Salary'].mean()).round(2)

Team
Atlanta Hawks             4860196.67
Boston Celtics            4181504.86
Brooklyn Nets             3501898.33
Charlotte Hornets         5222728.00
Chicago Bulls             5785558.53
Cleveland Cavaliers       7642049.21
Dallas Mavericks          4746582.13
Denver Nuggets            4294423.57
Detroit Pistons           4477884.20
Golden State Warriors     5924599.80
Houston Rockets           5018868.07
Indiana Pacers            4450121.73
Los Angeles Clippers      6323642.67
Los Angeles Lakers        4784695.40
Memphis Grizzlies         5467920.00
Miami Heat                6347359.46
Milwaukee Bucks           4350219.81
Minnesota Timberwolves    4593053.62
New Orleans Pelicans      4355303.89
New York Knicks           4581493.62
Oklahoma City Thunder     6251019.87
Orlando Magic             4297247.86
Philadelphia 76ers        2213778.14
Phoenix Suns              4229675.67
Portland Trail Blazers    3220121.20
Sacramento Kings          4778911.07
San Antonio Spurs         5629515.53
Toronto Raptors           4741174.07
Utah Jazz                 4204006.07
Washington Wizards        5088575.73
Name: Salary, dtype: float64