In [37]:
import pandas as pd

In [38]:
batch_1= pd.DataFrame([
(101, "London", 45.50, "complete"),
(102, "Manchester", -5.00, "complete"),
],columns=['order_id', 'City', 'Amount', 'Status'])
batch_2= pd.DataFrame([
(103, " Bristol ", 30.00, "complete"),
(104, "Leeds", 20.00, "cancelled"),
],columns=['order_id', 'City', 'Amount', 'Status'])
batch_3=pd.DataFrame([
(101, "London", 45.50, "complete"),
(105, "Manchester", 51.00, "complete"),
],columns=['order_id', 'City', 'Amount', 'Status'])

print(batch_1)
print(batch_2)
print(batch_3)

   order_id        City  Amount    Status
0       101      London    45.5  complete
1       102  Manchester    -5.0  complete
   order_id       City  Amount     Status
0       103   Bristol     30.0   complete
1       104      Leeds    20.0  cancelled
   order_id        City  Amount    Status
0       101      London    45.5  complete
1       105  Manchester    51.0  complete

In [39]:
bronze_df= pd.concat([batch_1, batch_2, batch_3], ignore_index=True)
print(bronze_df)

   order_id        City  Amount     Status
0       101      London    45.5   complete
1       102  Manchester    -5.0   complete
2       103    Bristol     30.0   complete
3       104       Leeds    20.0  cancelled
4       101      London    45.5   complete
5       105  Manchester    51.0   complete

In [40]:
bronze_df.shape

(6, 4)

In [41]:
# removing duplicates
silver_df= bronze_df.copy()
silver_df.drop_duplicates(subset= ['order_id'], keep= 'first', inplace= True)
silver_df

   order_id        City  Amount     Status
0       101      London    45.5   complete
1       102  Manchester    -5.0   complete
2       103    Bristol     30.0   complete
3       104       Leeds    20.0  cancelled
5       105  Manchester    51.0   complete

In [42]:
silver_df.shape

(5, 4)

In [43]:
silver_df= silver_df[silver_df['Amount'] > 0].astype({'Amount':int})
silver_df

   order_id        City  Amount     Status
0       101      London      45   complete
2       103    Bristol       30   complete
3       104       Leeds      20  cancelled
5       105  Manchester      51   complete

In [44]:
silver_df.shape

(4, 4)

In [45]:
silver_df['City']= silver_df['City'].str.strip()

In [46]:
silver_df.shape

(4, 4)

After data validation now the dataset has 4 rows and 4 columns as compared to the raw data which had 6 rows and 4 columns.

Q. 9 — Build a Gold Summary

In [50]:
gold_df= silver_df.copy()
gold_df

   order_id        City  Amount     Status
0       101      London      45   complete
2       103     Bristol      30   complete
3       104       Leeds      20  cancelled
5       105  Manchester      51   complete

In [53]:
gold_df= gold_df[gold_df['Status']=='complete']  # keep only the completed orders
gold_df

   order_id        City  Amount    Status
0       101      London      45  complete
2       103     Bristol      30  complete
5       105  Manchester      51  complete

In [49]:
gold_df

   order_id        City  Amount    Status
0       101      London      45  complete
2       103     Bristol      30  complete
3       104       Leeds      20  complete
5       105  Manchester      51  complete

In [54]:
gold_df.groupby('City')['Amount'].sum() # Calculating revenue by city

City
Bristol       30
London        45
Manchester    51
Name: Amount, dtype: int64

In [55]:
gold_df.groupby('City')['Amount'].sum().sort_values(ascending=False) # sort highest value first

City
Manchester    51
London        45
Bristol       30
Name: Amount, dtype: int64